// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: room.seat.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// 嘉宾位状态
public enum DGCLive_SeatStatus: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// 空闲
  case csOpen // = 0

  /// 关闭
  case csClose // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .csOpen
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .csOpen
    case 1: self = .csClose
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .csOpen: return 0
    case .csClose: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCLive_SeatStatus: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCLive_SeatStatus] = [
    .csOpen,
    .csClose,
  ]
}

#endif  // swift(>=4.2)

public enum DGCLive_ClearSeatType: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// 占位不用
  case cctZero // = 0

  /// 清空座位
  case cctClearSeat // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .cctZero
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .cctZero
    case 1: self = .cctClearSeat
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .cctZero: return 0
    case .cctClearSeat: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCLive_ClearSeatType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCLive_ClearSeatType] = [
    .cctZero,
    .cctClearSeat,
  ]
}

#endif  // swift(>=4.2)

public enum DGCLive_SitSeatType: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// 普通上麦
  case sctNormalSit // = 0

  /// 匿名上麦
  case sctMaskSit // = 1

  /// 遵循上一次，后台用
  case sctFollowLast // = 2

  ///移动类型
  case sctMove // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .sctNormalSit
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .sctNormalSit
    case 1: self = .sctMaskSit
    case 2: self = .sctFollowLast
    case 3: self = .sctMove
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .sctNormalSit: return 0
    case .sctMaskSit: return 1
    case .sctFollowLast: return 2
    case .sctMove: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCLive_SitSeatType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCLive_SitSeatType] = [
    .sctNormalSit,
    .sctMaskSit,
    .sctFollowLast,
    .sctMove,
  ]
}

#endif  // swift(>=4.2)

/// 麦位锁定状态
public enum DGCLive_ChairLockStatus: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// 打开状态
  case `open` // = 0

  /// 锁定状态
  case close // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .open
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .open
    case 1: self = .close
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .open: return 0
    case .close: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCLive_ChairLockStatus: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCLive_ChairLockStatus] = [
    .open,
    .close,
  ]
}

#endif  // swift(>=4.2)

public enum DGCLive_ChairQueueOpCode: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  ///占位
  case cqoZero // = 0

  ///请求连麦
  case cqoRequest // = 1

  ///同意连麦
  case cqoAgree // = 2

  ///拒绝连麦
  case cqoRefuse // = 3

  ///邀请连麦
  case cqoInvite // = 4

  ///取消连麦
  case cqoCancel // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .cqoZero
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .cqoZero
    case 1: self = .cqoRequest
    case 2: self = .cqoAgree
    case 3: self = .cqoRefuse
    case 4: self = .cqoInvite
    case 5: self = .cqoCancel
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .cqoZero: return 0
    case .cqoRequest: return 1
    case .cqoAgree: return 2
    case .cqoRefuse: return 3
    case .cqoInvite: return 4
    case .cqoCancel: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCLive_ChairQueueOpCode: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCLive_ChairQueueOpCode] = [
    .cqoZero,
    .cqoRequest,
    .cqoAgree,
    .cqoRefuse,
    .cqoInvite,
    .cqoCancel,
  ]
}

#endif  // swift(>=4.2)

public enum DGCLive_ChairQueueCMD: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case cqcZero // = 0

  ///申请连麦
  case cqcRequest // = 1

  ///同意连麦
  case cqcAgree // = 2

  ///拒绝连麦
  case cqcRefuse // = 3

  ///邀请连麦
  case cqcInvite // = 4

  ///取消连麦
  case cqcCancel // = 5

  ///管理员房主同步连麦数据
  case cqcSyncData // = 6
  case UNRECOGNIZED(Int)

  public init() {
    self = .cqcZero
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .cqcZero
    case 1: self = .cqcRequest
    case 2: self = .cqcAgree
    case 3: self = .cqcRefuse
    case 4: self = .cqcInvite
    case 5: self = .cqcCancel
    case 6: self = .cqcSyncData
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .cqcZero: return 0
    case .cqcRequest: return 1
    case .cqcAgree: return 2
    case .cqcRefuse: return 3
    case .cqcInvite: return 4
    case .cqcCancel: return 5
    case .cqcSyncData: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCLive_ChairQueueCMD: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCLive_ChairQueueCMD] = [
    .cqcZero,
    .cqcRequest,
    .cqcAgree,
    .cqcRefuse,
    .cqcInvite,
    .cqcCancel,
    .cqcSyncData,
  ]
}

#endif  // swift(>=4.2)

/// 嘉宾位
public struct DGCLive_Seat {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 座位ID, 0到8， 0是房主位
  public var id: Int32 = 0

  public var status: DGCLive_SeatStatus = .csOpen

  /// 位置上的玩家
  public var player: DGCLive_LivePlayer {
    get {return _player ?? DGCLive_LivePlayer()}
    set {_player = newValue}
  }
  /// Returns true if `player` has been explicitly set.
  public var hasPlayer: Bool {return self._player != nil}
  /// Clears the value of `player`. Subsequent reads from it will return its default value.
  public mutating func clearPlayer() {self._player = nil}

  /// 操作者ID
  public var `operator`: Int64 = 0

  /// 帽子等级
  public var goldLevel: Int32 = 0

  /// 麦序魅力值
  public var seatCharm: Int32 = 0

  ///排名
  public var seatCharmRank: Int32 = 0

  /// 是否是静音状态，true为静音
  public var muted: Bool = false

  public var cpID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _player: DGCLive_LivePlayer? = nil
}

/// 请求下座
public struct DGCLive_SeatLeaveReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 下座目标id
  public var targetID: Int64 = 0

  /// 座位ID
  public var seatID: Int32 = 0

  public var optType: DGCLive_ClearSeatType = .cctZero

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///  AgodaKey agoda_key = 2; // 声网key
public struct DGCLive_SeatLeaveRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 移麦
public struct DGCLive_SeatMoveReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var fromSeatID: Int32 = 0

  /// 移到位置
  public var toSeatID: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_SeatMoveRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 请求上麦
public struct DGCLive_SeatSitReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///麦位Id
  public var seatID: Int32 = 0

  ///上麦来源 0:正常上麦 1:邀请上麦
  public var source: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///  AgodaKey agoda_key = 2; // 声网key
public struct DGCLive_SeatSitRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// cmdId=100102, 广播嘉宾位状态变更
public struct DGCLive_BroadcastSeatStatus {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 座位ID
  public var seatID: Int32 = 0

  public var status: DGCLive_SeatStatus = .csOpen

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// cmdId=100110, 广播嘉宾位玩家变更
public struct DGCLive_BroadcastSeat {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 座位ID
  public var seatID: Int32 = 0

  public var seat: DGCLive_Seat {
    get {return _seat ?? DGCLive_Seat()}
    set {_seat = newValue}
  }
  /// Returns true if `seat` has been explicitly set.
  public var hasSeat: Bool {return self._seat != nil}
  /// Clears the value of `seat`. Subsequent reads from it will return its default value.
  public mutating func clearSeat() {self._seat = nil}

  /// 房间id; 之前的逻辑默认0
  public var roomID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _seat: DGCLive_Seat? = nil
}

/// 通知 上座者收到 cmdId=100111,
public struct DGCLive_BroadcastSeatSit {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 操作者id
  public var operatorID: Int64 = 0

  /// 上座目标id
  public var targetID: Int64 = 0

  /// 座位ID
  public var seatID: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// cmdId=100113 通知 下座者收到
public struct DGCLive_BroadcastSeatLeave {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 操作者id
  public var operatorID: Int64 = 0

  /// 下座目标id
  public var targetID: Int64 = 0

  /// 座位ID
  public var seatID: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// cmdId=100104, 广播禁麦/开麦
public struct DGCLive_BroadcastSeatSpeak {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 目标id
  public var targetID: Int64 = 0

  /// 坑位发言状态，0开/1禁
  public var seatBanSpeak: Bool = false

  ///坑位设备类型 0麦1摄像头
  public var device: DGCLive_SeatSetType = .utMic

  /// 目标名字
  public var targetName: String = String()

  /// 操作者Id
  public var operatorID: Int64 = 0

  /// 操作者名字
  public var operatorName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// cmdId=Seat 广播移麦
public struct DGCLive_BroadcastSeatMove {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var playerID: Int64 = 0

  public var fromSeatID: Int32 = 0

  /// 移到位置
  public var toSeatID: Int32 = 0

  /// 麦序魅力值
  public var seatCharm: Int32 = 0

  /// 麦序排行
  public var seatCharmRank: Int32 = 0

  /// 移麦者的cp_id
  public var cpID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 设置坑位发言开关
public struct DGCLive_SeatSpeakOnOffReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var device: DGCLive_SeatSetType = .utMic

  /// 坑位发言状态，
  public var seatSpeakOnoff: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_SeatSpeakOnOffRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// cmdId=100105, 广播设置坑位发言开关
public struct DGCLive_BroadcastChairSpeakOnOff {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 目标id
  public var targetID: Int64 = 0

  public var seatSpeakOnoff: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 邀请上麦
public struct DGCLive_InviteChairReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 被邀请人
  public var playerID: Int64 = 0

  /// 麦位Id（-1表示未指定麦位）
  public var chairID: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_InviteChairRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///cmd：110006
public struct DGCLive_InviteChairNotify {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inviterID: Int64 = 0

  public var inviterName: String = String()

  public var req: DGCLive_InviteChairReq {
    get {return _req ?? DGCLive_InviteChairReq()}
    set {_req = newValue}
  }
  /// Returns true if `req` has been explicitly set.
  public var hasReq: Bool {return self._req != nil}
  /// Clears the value of `req`. Subsequent reads from it will return its default value.
  public mutating func clearReq() {self._req = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _req: DGCLive_InviteChairReq? = nil
}

public struct DGCLive_KickChairReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 被踢的人
  public var playerID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_KickChairRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// cmd：110007
public struct DGCLive_KickChairNotify {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var `operator`: Int64 = 0

  public var operatorName: String = String()

  public var playerID: Int64 = 0

  public var chairID: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// cmd: 30020 静音麦位
public struct DGCLive_MuteChairReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var chairID: Int32 = 0

  ///true表示静音
  public var muted: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_MuteChairRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///cmd 110008
public struct DGCLive_MuteChairNotify {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var chairID: Int32 = 0

  public var muted: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// cmd: 30021 锁定麦位
public struct DGCLive_LockChairReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///-1 表示全部麦位
  public var chairID: Int32 = 0

  public var status: DGCLive_ChairLockStatus = .open

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_LockChairRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// cmdId=110009, 广播麦位锁定状态变更
public struct DGCLive_ChairLockStatusNotify {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var chairID: [Int32] = []

  public var status: DGCLive_ChairLockStatus = .open

  /// 本次操作涉及到麦位上的用户（如果麦位上有人的话）
  public var players: [Int64] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_OptChairQueueExt {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// PK模式下申请要上的阵营
  public var pkTeam: DGCLive_PkTeamName = .pkTeamNone

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 连麦操作
public struct DGCLive_OptChairQueueReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var op: DGCLive_ChairQueueOpCode = .cqoZero

  public var playerID: Int64 = 0

  public var ext: DGCLive_OptChairQueueExt {
    get {return _ext ?? DGCLive_OptChairQueueExt()}
    set {_ext = newValue}
  }
  /// Returns true if `ext` has been explicitly set.
  public var hasExt: Bool {return self._ext != nil}
  /// Clears the value of `ext`. Subsequent reads from it will return its default value.
  public mutating func clearExt() {self._ext = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _ext: DGCLive_OptChairQueueExt? = nil
}

public struct DGCLive_OptChairQueueRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// cmdId=100115, 连麦广播
public struct DGCLive_BroadcastChairQueueOpt {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var cmd: DGCLive_ChairQueueCMD = .cqcZero

  /// 队列人数
  public var queueLen: Int64 = 0

  /// 名称
  public var ownerName: String = String()

  ///管理员或房主id
  public var playerID: Int64 = 0

  ///被操作者
  public var targetID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 请求排麦列表
public struct DGCLive_ChairQueueListReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_ChairQueueListRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var queue: [DGCLive_LivePlayer] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_AcceptChairQueueReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 1. 同意, 2. 拒绝
  public var status: UInt32 = 0

  /// 1. 打开, 2. 关闭
  public var isCameraOn: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_AcceptChairQueueRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///  100103 麦位发生变动广播麦位列表
public struct DGCLive_BroadcastSeatQueue {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var seats: [DGCLive_Seat] = []

  /// 房间Id; 之前的逻辑默认0
  public var roomID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension DGCLive_SeatStatus: @unchecked Sendable {}
extension DGCLive_ClearSeatType: @unchecked Sendable {}
extension DGCLive_SitSeatType: @unchecked Sendable {}
extension DGCLive_ChairLockStatus: @unchecked Sendable {}
extension DGCLive_ChairQueueOpCode: @unchecked Sendable {}
extension DGCLive_ChairQueueCMD: @unchecked Sendable {}
extension DGCLive_Seat: @unchecked Sendable {}
extension DGCLive_SeatLeaveReq: @unchecked Sendable {}
extension DGCLive_SeatLeaveRes: @unchecked Sendable {}
extension DGCLive_SeatMoveReq: @unchecked Sendable {}
extension DGCLive_SeatMoveRes: @unchecked Sendable {}
extension DGCLive_SeatSitReq: @unchecked Sendable {}
extension DGCLive_SeatSitRes: @unchecked Sendable {}
extension DGCLive_BroadcastSeatStatus: @unchecked Sendable {}
extension DGCLive_BroadcastSeat: @unchecked Sendable {}
extension DGCLive_BroadcastSeatSit: @unchecked Sendable {}
extension DGCLive_BroadcastSeatLeave: @unchecked Sendable {}
extension DGCLive_BroadcastSeatSpeak: @unchecked Sendable {}
extension DGCLive_BroadcastSeatMove: @unchecked Sendable {}
extension DGCLive_SeatSpeakOnOffReq: @unchecked Sendable {}
extension DGCLive_SeatSpeakOnOffRes: @unchecked Sendable {}
extension DGCLive_BroadcastChairSpeakOnOff: @unchecked Sendable {}
extension DGCLive_InviteChairReq: @unchecked Sendable {}
extension DGCLive_InviteChairRes: @unchecked Sendable {}
extension DGCLive_InviteChairNotify: @unchecked Sendable {}
extension DGCLive_KickChairReq: @unchecked Sendable {}
extension DGCLive_KickChairRes: @unchecked Sendable {}
extension DGCLive_KickChairNotify: @unchecked Sendable {}
extension DGCLive_MuteChairReq: @unchecked Sendable {}
extension DGCLive_MuteChairRes: @unchecked Sendable {}
extension DGCLive_MuteChairNotify: @unchecked Sendable {}
extension DGCLive_LockChairReq: @unchecked Sendable {}
extension DGCLive_LockChairRes: @unchecked Sendable {}
extension DGCLive_ChairLockStatusNotify: @unchecked Sendable {}
extension DGCLive_OptChairQueueExt: @unchecked Sendable {}
extension DGCLive_OptChairQueueReq: @unchecked Sendable {}
extension DGCLive_OptChairQueueRes: @unchecked Sendable {}
extension DGCLive_BroadcastChairQueueOpt: @unchecked Sendable {}
extension DGCLive_ChairQueueListReq: @unchecked Sendable {}
extension DGCLive_ChairQueueListRes: @unchecked Sendable {}
extension DGCLive_AcceptChairQueueReq: @unchecked Sendable {}
extension DGCLive_AcceptChairQueueRes: @unchecked Sendable {}
extension DGCLive_BroadcastSeatQueue: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "live"

extension DGCLive_SeatStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CS_OPEN"),
    1: .same(proto: "CS_CLOSE"),
  ]
}

extension DGCLive_ClearSeatType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CCT_ZERO"),
    1: .same(proto: "CCT_CLEAR_Seat"),
  ]
}

extension DGCLive_SitSeatType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SCT_NormalSit"),
    1: .same(proto: "SCT_MaskSit"),
    2: .same(proto: "SCT_FollowLast"),
    3: .same(proto: "SCT_MOVE"),
  ]
}

extension DGCLive_ChairLockStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "OPEN"),
    1: .same(proto: "CLOSE"),
  ]
}

extension DGCLive_ChairQueueOpCode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CQO_Zero"),
    1: .same(proto: "CQO_Request"),
    2: .same(proto: "CQO_AGREE"),
    3: .same(proto: "CQO_REFUSE"),
    4: .same(proto: "CQO_INVITE"),
    5: .same(proto: "CQO_CANCEL"),
  ]
}

extension DGCLive_ChairQueueCMD: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CQC_Zero"),
    1: .same(proto: "CQC_REQUEST"),
    2: .same(proto: "CQC_AGREE"),
    3: .same(proto: "CQC_REFUSE"),
    4: .same(proto: "CQC_INVITE"),
    5: .same(proto: "CQC_CANCEL"),
    6: .same(proto: "CQC_SYNC_Data"),
  ]
}

extension DGCLive_Seat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Seat"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "status"),
    3: .same(proto: "player"),
    4: .same(proto: "operator"),
    5: .standard(proto: "gold_level"),
    6: .standard(proto: "seat_charm"),
    7: .standard(proto: "seat_charm_rank"),
    8: .same(proto: "muted"),
    9: .standard(proto: "cp_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt32Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._player) }()
      case 4: try { try decoder.decodeSingularSInt64Field(value: &self.`operator`) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.goldLevel) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.seatCharm) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.seatCharmRank) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.muted) }()
      case 9: try { try decoder.decodeSingularInt64Field(value: &self.cpID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.id != 0 {
      try visitor.visitSingularSInt32Field(value: self.id, fieldNumber: 1)
    }
    if self.status != .csOpen {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    try { if let dgc_v = self._player {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 3)
    } }()
    if self.`operator` != 0 {
      try visitor.visitSingularSInt64Field(value: self.`operator`, fieldNumber: 4)
    }
    if self.goldLevel != 0 {
      try visitor.visitSingularInt32Field(value: self.goldLevel, fieldNumber: 5)
    }
    if self.seatCharm != 0 {
      try visitor.visitSingularInt32Field(value: self.seatCharm, fieldNumber: 6)
    }
    if self.seatCharmRank != 0 {
      try visitor.visitSingularInt32Field(value: self.seatCharmRank, fieldNumber: 7)
    }
    if self.muted != false {
      try visitor.visitSingularBoolField(value: self.muted, fieldNumber: 8)
    }
    if self.cpID != 0 {
      try visitor.visitSingularInt64Field(value: self.cpID, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_Seat, rhs: DGCLive_Seat) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.status != rhs.status {return false}
    if lhs._player != rhs._player {return false}
    if lhs.`operator` != rhs.`operator` {return false}
    if lhs.goldLevel != rhs.goldLevel {return false}
    if lhs.seatCharm != rhs.seatCharm {return false}
    if lhs.seatCharmRank != rhs.seatCharmRank {return false}
    if lhs.muted != rhs.muted {return false}
    if lhs.cpID != rhs.cpID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_SeatLeaveReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SeatLeaveReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .standard(proto: "target_id"),
    3: .standard(proto: "Seat_id"),
    4: .standard(proto: "opt_type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 2: try { try decoder.decodeSingularSInt64Field(value: &self.targetID) }()
      case 3: try { try decoder.decodeSingularSInt32Field(value: &self.seatID) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.optType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.targetID != 0 {
      try visitor.visitSingularSInt64Field(value: self.targetID, fieldNumber: 2)
    }
    if self.seatID != 0 {
      try visitor.visitSingularSInt32Field(value: self.seatID, fieldNumber: 3)
    }
    if self.optType != .cctZero {
      try visitor.visitSingularEnumField(value: self.optType, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_SeatLeaveReq, rhs: DGCLive_SeatLeaveReq) -> Bool {
    if lhs.targetID != rhs.targetID {return false}
    if lhs.seatID != rhs.seatID {return false}
    if lhs.optType != rhs.optType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_SeatLeaveRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SeatLeaveRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_SeatLeaveRes, rhs: DGCLive_SeatLeaveRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_SeatMoveReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SeatMoveReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .standard(proto: "from_Seat_id"),
    3: .standard(proto: "to_Seat_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 2: try { try decoder.decodeSingularSInt32Field(value: &self.fromSeatID) }()
      case 3: try { try decoder.decodeSingularSInt32Field(value: &self.toSeatID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.fromSeatID != 0 {
      try visitor.visitSingularSInt32Field(value: self.fromSeatID, fieldNumber: 2)
    }
    if self.toSeatID != 0 {
      try visitor.visitSingularSInt32Field(value: self.toSeatID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_SeatMoveReq, rhs: DGCLive_SeatMoveReq) -> Bool {
    if lhs.fromSeatID != rhs.fromSeatID {return false}
    if lhs.toSeatID != rhs.toSeatID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_SeatMoveRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SeatMoveRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_SeatMoveRes, rhs: DGCLive_SeatMoveRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_SeatSitReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SeatSitReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "Seat_id"),
    2: .same(proto: "source"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.seatID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.source) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.seatID != 0 {
      try visitor.visitSingularInt32Field(value: self.seatID, fieldNumber: 1)
    }
    if self.source != 0 {
      try visitor.visitSingularInt32Field(value: self.source, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_SeatSitReq, rhs: DGCLive_SeatSitReq) -> Bool {
    if lhs.seatID != rhs.seatID {return false}
    if lhs.source != rhs.source {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_SeatSitRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SeatSitRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_SeatSitRes, rhs: DGCLive_SeatSitRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_BroadcastSeatStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastSeatStatus"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "Seat_id"),
    2: .same(proto: "status"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt32Field(value: &self.seatID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.seatID != 0 {
      try visitor.visitSingularSInt32Field(value: self.seatID, fieldNumber: 1)
    }
    if self.status != .csOpen {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_BroadcastSeatStatus, rhs: DGCLive_BroadcastSeatStatus) -> Bool {
    if lhs.seatID != rhs.seatID {return false}
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_BroadcastSeat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastSeat"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "Seat_id"),
    2: .same(proto: "Seat"),
    3: .same(proto: "roomId"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt32Field(value: &self.seatID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._seat) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.roomID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.seatID != 0 {
      try visitor.visitSingularSInt32Field(value: self.seatID, fieldNumber: 1)
    }
    try { if let dgc_v = self._seat {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 2)
    } }()
    if self.roomID != 0 {
      try visitor.visitSingularInt64Field(value: self.roomID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_BroadcastSeat, rhs: DGCLive_BroadcastSeat) -> Bool {
    if lhs.seatID != rhs.seatID {return false}
    if lhs._seat != rhs._seat {return false}
    if lhs.roomID != rhs.roomID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_BroadcastSeatSit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastSeatSit"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "operator_id"),
    2: .standard(proto: "target_id"),
    3: .standard(proto: "seat_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt64Field(value: &self.operatorID) }()
      case 2: try { try decoder.decodeSingularSInt64Field(value: &self.targetID) }()
      case 3: try { try decoder.decodeSingularSInt32Field(value: &self.seatID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.operatorID != 0 {
      try visitor.visitSingularSInt64Field(value: self.operatorID, fieldNumber: 1)
    }
    if self.targetID != 0 {
      try visitor.visitSingularSInt64Field(value: self.targetID, fieldNumber: 2)
    }
    if self.seatID != 0 {
      try visitor.visitSingularSInt32Field(value: self.seatID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_BroadcastSeatSit, rhs: DGCLive_BroadcastSeatSit) -> Bool {
    if lhs.operatorID != rhs.operatorID {return false}
    if lhs.targetID != rhs.targetID {return false}
    if lhs.seatID != rhs.seatID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_BroadcastSeatLeave: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastSeatLeave"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "operator_id"),
    2: .standard(proto: "target_id"),
    3: .standard(proto: "Seat_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt64Field(value: &self.operatorID) }()
      case 2: try { try decoder.decodeSingularSInt64Field(value: &self.targetID) }()
      case 3: try { try decoder.decodeSingularSInt32Field(value: &self.seatID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.operatorID != 0 {
      try visitor.visitSingularSInt64Field(value: self.operatorID, fieldNumber: 1)
    }
    if self.targetID != 0 {
      try visitor.visitSingularSInt64Field(value: self.targetID, fieldNumber: 2)
    }
    if self.seatID != 0 {
      try visitor.visitSingularSInt32Field(value: self.seatID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_BroadcastSeatLeave, rhs: DGCLive_BroadcastSeatLeave) -> Bool {
    if lhs.operatorID != rhs.operatorID {return false}
    if lhs.targetID != rhs.targetID {return false}
    if lhs.seatID != rhs.seatID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_BroadcastSeatSpeak: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastSeatSpeak"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "target_id"),
    2: .standard(proto: "Seat_ban_speak"),
    3: .same(proto: "device"),
    4: .standard(proto: "target_name"),
    5: .standard(proto: "operator_id"),
    6: .standard(proto: "operator_name"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt64Field(value: &self.targetID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.seatBanSpeak) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.device) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.targetName) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.operatorID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.operatorName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.targetID != 0 {
      try visitor.visitSingularSInt64Field(value: self.targetID, fieldNumber: 1)
    }
    if self.seatBanSpeak != false {
      try visitor.visitSingularBoolField(value: self.seatBanSpeak, fieldNumber: 2)
    }
    if self.device != .utMic {
      try visitor.visitSingularEnumField(value: self.device, fieldNumber: 3)
    }
    if !self.targetName.isEmpty {
      try visitor.visitSingularStringField(value: self.targetName, fieldNumber: 4)
    }
    if self.operatorID != 0 {
      try visitor.visitSingularInt64Field(value: self.operatorID, fieldNumber: 5)
    }
    if !self.operatorName.isEmpty {
      try visitor.visitSingularStringField(value: self.operatorName, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_BroadcastSeatSpeak, rhs: DGCLive_BroadcastSeatSpeak) -> Bool {
    if lhs.targetID != rhs.targetID {return false}
    if lhs.seatBanSpeak != rhs.seatBanSpeak {return false}
    if lhs.device != rhs.device {return false}
    if lhs.targetName != rhs.targetName {return false}
    if lhs.operatorID != rhs.operatorID {return false}
    if lhs.operatorName != rhs.operatorName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_BroadcastSeatMove: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastSeatMove"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "player_id"),
    2: .standard(proto: "from_Seat_id"),
    3: .standard(proto: "to_Seat_id"),
    4: .standard(proto: "Seat_charm"),
    5: .standard(proto: "Seat_charm_rank"),
    6: .standard(proto: "cp_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt64Field(value: &self.playerID) }()
      case 2: try { try decoder.decodeSingularSInt32Field(value: &self.fromSeatID) }()
      case 3: try { try decoder.decodeSingularSInt32Field(value: &self.toSeatID) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.seatCharm) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.seatCharmRank) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.cpID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.playerID != 0 {
      try visitor.visitSingularSInt64Field(value: self.playerID, fieldNumber: 1)
    }
    if self.fromSeatID != 0 {
      try visitor.visitSingularSInt32Field(value: self.fromSeatID, fieldNumber: 2)
    }
    if self.toSeatID != 0 {
      try visitor.visitSingularSInt32Field(value: self.toSeatID, fieldNumber: 3)
    }
    if self.seatCharm != 0 {
      try visitor.visitSingularInt32Field(value: self.seatCharm, fieldNumber: 4)
    }
    if self.seatCharmRank != 0 {
      try visitor.visitSingularInt32Field(value: self.seatCharmRank, fieldNumber: 5)
    }
    if self.cpID != 0 {
      try visitor.visitSingularInt64Field(value: self.cpID, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_BroadcastSeatMove, rhs: DGCLive_BroadcastSeatMove) -> Bool {
    if lhs.playerID != rhs.playerID {return false}
    if lhs.fromSeatID != rhs.fromSeatID {return false}
    if lhs.toSeatID != rhs.toSeatID {return false}
    if lhs.seatCharm != rhs.seatCharm {return false}
    if lhs.seatCharmRank != rhs.seatCharmRank {return false}
    if lhs.cpID != rhs.cpID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_SeatSpeakOnOffReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SeatSpeakOnOffReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "device"),
    2: .standard(proto: "Seat_speak_onoff"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.device) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.seatSpeakOnoff) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.device != .utMic {
      try visitor.visitSingularEnumField(value: self.device, fieldNumber: 1)
    }
    if self.seatSpeakOnoff != false {
      try visitor.visitSingularBoolField(value: self.seatSpeakOnoff, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_SeatSpeakOnOffReq, rhs: DGCLive_SeatSpeakOnOffReq) -> Bool {
    if lhs.device != rhs.device {return false}
    if lhs.seatSpeakOnoff != rhs.seatSpeakOnoff {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_SeatSpeakOnOffRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SeatSpeakOnOffRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_SeatSpeakOnOffRes, rhs: DGCLive_SeatSpeakOnOffRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_BroadcastChairSpeakOnOff: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastChairSpeakOnOff"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "target_id"),
    2: .standard(proto: "Seat_speak_onoff"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt64Field(value: &self.targetID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.seatSpeakOnoff) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.targetID != 0 {
      try visitor.visitSingularSInt64Field(value: self.targetID, fieldNumber: 1)
    }
    if self.seatSpeakOnoff != false {
      try visitor.visitSingularBoolField(value: self.seatSpeakOnoff, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_BroadcastChairSpeakOnOff, rhs: DGCLive_BroadcastChairSpeakOnOff) -> Bool {
    if lhs.targetID != rhs.targetID {return false}
    if lhs.seatSpeakOnoff != rhs.seatSpeakOnoff {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_InviteChairReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InviteChairReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "player_id"),
    2: .standard(proto: "chair_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.playerID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.chairID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.playerID != 0 {
      try visitor.visitSingularInt64Field(value: self.playerID, fieldNumber: 1)
    }
    if self.chairID != 0 {
      try visitor.visitSingularInt32Field(value: self.chairID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_InviteChairReq, rhs: DGCLive_InviteChairReq) -> Bool {
    if lhs.playerID != rhs.playerID {return false}
    if lhs.chairID != rhs.chairID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_InviteChairRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InviteChairRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_InviteChairRes, rhs: DGCLive_InviteChairRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_InviteChairNotify: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InviteChairNotify"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "inviter_id"),
    2: .standard(proto: "inviter_name"),
    3: .same(proto: "req"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.inviterID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.inviterName) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._req) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.inviterID != 0 {
      try visitor.visitSingularInt64Field(value: self.inviterID, fieldNumber: 1)
    }
    if !self.inviterName.isEmpty {
      try visitor.visitSingularStringField(value: self.inviterName, fieldNumber: 2)
    }
    try { if let dgc_v = self._req {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_InviteChairNotify, rhs: DGCLive_InviteChairNotify) -> Bool {
    if lhs.inviterID != rhs.inviterID {return false}
    if lhs.inviterName != rhs.inviterName {return false}
    if lhs._req != rhs._req {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_KickChairReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KickChairReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "player_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.playerID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.playerID != 0 {
      try visitor.visitSingularInt64Field(value: self.playerID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_KickChairReq, rhs: DGCLive_KickChairReq) -> Bool {
    if lhs.playerID != rhs.playerID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_KickChairRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KickChairRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_KickChairRes, rhs: DGCLive_KickChairRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_KickChairNotify: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KickChairNotify"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "operator"),
    2: .standard(proto: "operator_name"),
    3: .standard(proto: "player_id"),
    4: .standard(proto: "chair_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.`operator`) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.operatorName) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.playerID) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.chairID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.`operator` != 0 {
      try visitor.visitSingularInt64Field(value: self.`operator`, fieldNumber: 1)
    }
    if !self.operatorName.isEmpty {
      try visitor.visitSingularStringField(value: self.operatorName, fieldNumber: 2)
    }
    if self.playerID != 0 {
      try visitor.visitSingularInt64Field(value: self.playerID, fieldNumber: 3)
    }
    if self.chairID != 0 {
      try visitor.visitSingularInt32Field(value: self.chairID, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_KickChairNotify, rhs: DGCLive_KickChairNotify) -> Bool {
    if lhs.`operator` != rhs.`operator` {return false}
    if lhs.operatorName != rhs.operatorName {return false}
    if lhs.playerID != rhs.playerID {return false}
    if lhs.chairID != rhs.chairID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_MuteChairReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MuteChairReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chair_id"),
    2: .same(proto: "muted"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.chairID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.muted) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.chairID != 0 {
      try visitor.visitSingularInt32Field(value: self.chairID, fieldNumber: 1)
    }
    if self.muted != false {
      try visitor.visitSingularBoolField(value: self.muted, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_MuteChairReq, rhs: DGCLive_MuteChairReq) -> Bool {
    if lhs.chairID != rhs.chairID {return false}
    if lhs.muted != rhs.muted {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_MuteChairRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MuteChairRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_MuteChairRes, rhs: DGCLive_MuteChairRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_MuteChairNotify: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MuteChairNotify"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chair_id"),
    2: .same(proto: "muted"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.chairID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.muted) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.chairID != 0 {
      try visitor.visitSingularInt32Field(value: self.chairID, fieldNumber: 1)
    }
    if self.muted != false {
      try visitor.visitSingularBoolField(value: self.muted, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_MuteChairNotify, rhs: DGCLive_MuteChairNotify) -> Bool {
    if lhs.chairID != rhs.chairID {return false}
    if lhs.muted != rhs.muted {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_LockChairReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LockChairReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chair_id"),
    2: .same(proto: "status"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.chairID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.chairID != 0 {
      try visitor.visitSingularInt32Field(value: self.chairID, fieldNumber: 1)
    }
    if self.status != .open {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_LockChairReq, rhs: DGCLive_LockChairReq) -> Bool {
    if lhs.chairID != rhs.chairID {return false}
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_LockChairRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LockChairRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_LockChairRes, rhs: DGCLive_LockChairRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_ChairLockStatusNotify: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChairLockStatusNotify"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chair_id"),
    2: .same(proto: "status"),
    3: .same(proto: "players"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedInt32Field(value: &self.chairID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 3: try { try decoder.decodeRepeatedInt64Field(value: &self.players) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.chairID.isEmpty {
      try visitor.visitPackedInt32Field(value: self.chairID, fieldNumber: 1)
    }
    if self.status != .open {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    if !self.players.isEmpty {
      try visitor.visitPackedInt64Field(value: self.players, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_ChairLockStatusNotify, rhs: DGCLive_ChairLockStatusNotify) -> Bool {
    if lhs.chairID != rhs.chairID {return false}
    if lhs.status != rhs.status {return false}
    if lhs.players != rhs.players {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_OptChairQueueExt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OptChairQueueExt"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "pk_team"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.pkTeam) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pkTeam != .pkTeamNone {
      try visitor.visitSingularEnumField(value: self.pkTeam, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_OptChairQueueExt, rhs: DGCLive_OptChairQueueExt) -> Bool {
    if lhs.pkTeam != rhs.pkTeam {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_OptChairQueueReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OptChairQueueReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "op"),
    2: .standard(proto: "player_id"),
    3: .same(proto: "ext"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.op) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.playerID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._ext) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.op != .cqoZero {
      try visitor.visitSingularEnumField(value: self.op, fieldNumber: 1)
    }
    if self.playerID != 0 {
      try visitor.visitSingularInt64Field(value: self.playerID, fieldNumber: 2)
    }
    try { if let dgc_v = self._ext {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_OptChairQueueReq, rhs: DGCLive_OptChairQueueReq) -> Bool {
    if lhs.op != rhs.op {return false}
    if lhs.playerID != rhs.playerID {return false}
    if lhs._ext != rhs._ext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_OptChairQueueRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OptChairQueueRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_OptChairQueueRes, rhs: DGCLive_OptChairQueueRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_BroadcastChairQueueOpt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastChairQueueOpt"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "cmd"),
    2: .standard(proto: "queue_len"),
    3: .standard(proto: "owner_name"),
    4: .same(proto: "playerId"),
    5: .same(proto: "targetId"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.cmd) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.queueLen) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.ownerName) }()
      case 4: try { try decoder.decodeSingularSInt64Field(value: &self.playerID) }()
      case 5: try { try decoder.decodeSingularSInt64Field(value: &self.targetID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.cmd != .cqcZero {
      try visitor.visitSingularEnumField(value: self.cmd, fieldNumber: 1)
    }
    if self.queueLen != 0 {
      try visitor.visitSingularInt64Field(value: self.queueLen, fieldNumber: 2)
    }
    if !self.ownerName.isEmpty {
      try visitor.visitSingularStringField(value: self.ownerName, fieldNumber: 3)
    }
    if self.playerID != 0 {
      try visitor.visitSingularSInt64Field(value: self.playerID, fieldNumber: 4)
    }
    if self.targetID != 0 {
      try visitor.visitSingularSInt64Field(value: self.targetID, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_BroadcastChairQueueOpt, rhs: DGCLive_BroadcastChairQueueOpt) -> Bool {
    if lhs.cmd != rhs.cmd {return false}
    if lhs.queueLen != rhs.queueLen {return false}
    if lhs.ownerName != rhs.ownerName {return false}
    if lhs.playerID != rhs.playerID {return false}
    if lhs.targetID != rhs.targetID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_ChairQueueListReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChairQueueListReq"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_ChairQueueListReq, rhs: DGCLive_ChairQueueListReq) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_ChairQueueListRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChairQueueListRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "queue"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.queue) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.queue.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.queue, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_ChairQueueListRes, rhs: DGCLive_ChairQueueListRes) -> Bool {
    if lhs.queue != rhs.queue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_AcceptChairQueueReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AcceptChairQueueReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "status"),
    2: .standard(proto: "is_camera_on"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.status) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isCameraOn) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.status != 0 {
      try visitor.visitSingularUInt32Field(value: self.status, fieldNumber: 1)
    }
    if self.isCameraOn != false {
      try visitor.visitSingularBoolField(value: self.isCameraOn, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_AcceptChairQueueReq, rhs: DGCLive_AcceptChairQueueReq) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.isCameraOn != rhs.isCameraOn {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_AcceptChairQueueRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AcceptChairQueueRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_AcceptChairQueueRes, rhs: DGCLive_AcceptChairQueueRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_BroadcastSeatQueue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastSeatQueue"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "seats"),
    2: .same(proto: "roomId"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.seats) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.roomID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.seats.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.seats, fieldNumber: 1)
    }
    if self.roomID != 0 {
      try visitor.visitSingularInt64Field(value: self.roomID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_BroadcastSeatQueue, rhs: DGCLive_BroadcastSeatQueue) -> Bool {
    if lhs.seats != rhs.seats {return false}
    if lhs.roomID != rhs.roomID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
