// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: room.chair.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum DGCLive_SitChairType: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// 普通上麦
  case sctNormalSit // = 0

  /// 匿名上麦
  case sctMaskSit // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .sctNormalSit
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .sctNormalSit
    case 1: self = .sctMaskSit
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .sctNormalSit: return 0
    case .sctMaskSit: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCLive_SitChairType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCLive_SitChairType] = [
    .sctNormalSit,
    .sctMaskSit,
  ]
}

#endif  // swift(>=4.2)

/// 请求排麦列表 GetChairQueue
public struct DGCLive_ChairQueueReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_ChairQueueRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 排麦列表 （注：此ScenePlayer只有id，name, icon 3个字段可用）
  public var queue: [DGCLive_LivePlayer] = []

  /// 队列状态； false可排麦，true不可排麦
  public var banQueueStatus: Bool = false

  /// 请求列表者的序号，没有则返回-1
  public var ranking: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 加入/退出排麦 OptChairQueue
public struct DGCLive_ChairQueueOptReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 0加入，1退出
  public var type: UInt32 = 0

  /// 被添加/移除排麦的目标id， 当!=0时，被管理员插入队列
  public var targetID: Int64 = 0

  /// 排麦类型
  public var sitType: DGCLive_SitChairType = .sctNormalSit

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_ChairQueueOptRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 排麦插队 JumpChairQueue
public struct DGCLive_ChairQueueJumpReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 目标用户id
  public var targetID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_ChairQueueJumpRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///设置房间上麦模式 SwitchRoomChairMode
public struct DGCLive_SwitchRoomChairModeReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 0：自由模式；1：排麦模式
  public var modeType: DGCLive_SeatModeType = .chairModeTypeFree

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLive_SwitchRoomChairModeRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///CmdId=100202
public struct DGCLive_RoomChairModeChange {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 0：自由模式；1：排麦模式
  public var modeType: DGCLive_SeatModeType = .chairModeTypeFree

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///cmdId = 110013 
///房间权限变更
public struct DGCLive_BroadCastRightChange {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///1：增加 2：移除
  public var addOrRemove: Int32 = 0

  ///权限代码 1: 视频模式
  public var rightCode: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension DGCLive_SitChairType: @unchecked Sendable {}
extension DGCLive_ChairQueueReq: @unchecked Sendable {}
extension DGCLive_ChairQueueRes: @unchecked Sendable {}
extension DGCLive_ChairQueueOptReq: @unchecked Sendable {}
extension DGCLive_ChairQueueOptRes: @unchecked Sendable {}
extension DGCLive_ChairQueueJumpReq: @unchecked Sendable {}
extension DGCLive_ChairQueueJumpRes: @unchecked Sendable {}
extension DGCLive_SwitchRoomChairModeReq: @unchecked Sendable {}
extension DGCLive_SwitchRoomChairModeRes: @unchecked Sendable {}
extension DGCLive_RoomChairModeChange: @unchecked Sendable {}
extension DGCLive_BroadCastRightChange: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "live"

extension DGCLive_SitChairType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SCT_NormalSit"),
    1: .same(proto: "SCT_MaskSit"),
  ]
}

extension DGCLive_ChairQueueReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChairQueueReq"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_ChairQueueReq, rhs: DGCLive_ChairQueueReq) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_ChairQueueRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChairQueueRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    14: .same(proto: "queue"),
    1: .standard(proto: "ban_queue_status"),
    2: .same(proto: "ranking"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.banQueueStatus) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.ranking) }()
      case 14: try { try decoder.decodeRepeatedMessageField(value: &self.queue) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.banQueueStatus != false {
      try visitor.visitSingularBoolField(value: self.banQueueStatus, fieldNumber: 1)
    }
    if self.ranking != 0 {
      try visitor.visitSingularInt32Field(value: self.ranking, fieldNumber: 2)
    }
    if !self.queue.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.queue, fieldNumber: 14)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_ChairQueueRes, rhs: DGCLive_ChairQueueRes) -> Bool {
    if lhs.queue != rhs.queue {return false}
    if lhs.banQueueStatus != rhs.banQueueStatus {return false}
    if lhs.ranking != rhs.ranking {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_ChairQueueOptReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChairQueueOptReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .same(proto: "type"),
    3: .standard(proto: "target_id"),
    4: .standard(proto: "sit_type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.type) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.targetID) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.sitType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != 0 {
      try visitor.visitSingularUInt32Field(value: self.type, fieldNumber: 2)
    }
    if self.targetID != 0 {
      try visitor.visitSingularInt64Field(value: self.targetID, fieldNumber: 3)
    }
    if self.sitType != .sctNormalSit {
      try visitor.visitSingularEnumField(value: self.sitType, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_ChairQueueOptReq, rhs: DGCLive_ChairQueueOptReq) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.targetID != rhs.targetID {return false}
    if lhs.sitType != rhs.sitType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_ChairQueueOptRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChairQueueOptRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_ChairQueueOptRes, rhs: DGCLive_ChairQueueOptRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_ChairQueueJumpReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChairQueueJumpReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .standard(proto: "target_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 2: try { try decoder.decodeSingularSInt64Field(value: &self.targetID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.targetID != 0 {
      try visitor.visitSingularSInt64Field(value: self.targetID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_ChairQueueJumpReq, rhs: DGCLive_ChairQueueJumpReq) -> Bool {
    if lhs.targetID != rhs.targetID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_ChairQueueJumpRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChairQueueJumpRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_ChairQueueJumpRes, rhs: DGCLive_ChairQueueJumpRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_SwitchRoomChairModeReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SwitchRoomChairModeReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "mode_type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.modeType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.modeType != .chairModeTypeFree {
      try visitor.visitSingularEnumField(value: self.modeType, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_SwitchRoomChairModeReq, rhs: DGCLive_SwitchRoomChairModeReq) -> Bool {
    if lhs.modeType != rhs.modeType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_SwitchRoomChairModeRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SwitchRoomChairModeRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_SwitchRoomChairModeRes, rhs: DGCLive_SwitchRoomChairModeRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_RoomChairModeChange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RoomChairModeChange"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "mode_type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.modeType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.modeType != .chairModeTypeFree {
      try visitor.visitSingularEnumField(value: self.modeType, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_RoomChairModeChange, rhs: DGCLive_RoomChairModeChange) -> Bool {
    if lhs.modeType != rhs.modeType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLive_BroadCastRightChange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadCastRightChange"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "add_or_remove"),
    2: .standard(proto: "right_code"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.addOrRemove) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.rightCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.addOrRemove != 0 {
      try visitor.visitSingularInt32Field(value: self.addOrRemove, fieldNumber: 1)
    }
    if self.rightCode != 0 {
      try visitor.visitSingularInt32Field(value: self.rightCode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLive_BroadCastRightChange, rhs: DGCLive_BroadCastRightChange) -> Bool {
    if lhs.addOrRemove != rhs.addOrRemove {return false}
    if lhs.rightCode != rhs.rightCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
