// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: friend.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum DGCFriend_OperType: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  ///占位
  case none2001 // = 0

  /// 关注
  case follow // = 1

  ///取消关注
  case unfollow // = 2

  ///屏蔽用户
  case block // = 3

  ///取消屏蔽
  case unblock // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .none2001
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .none2001
    case 1: self = .follow
    case 2: self = .unfollow
    case 3: self = .block
    case 4: self = .unblock
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .none2001: return 0
    case .follow: return 1
    case .unfollow: return 2
    case .block: return 3
    case .unblock: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCFriend_OperType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCFriend_OperType] = [
    .none2001,
    .follow,
    .unfollow,
    .block,
    .unblock,
  ]
}

#endif  // swift(>=4.2)

/// 好友类型：
public enum DGCFriend_FriendType: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// 陌生人
  case ftStranger // = 0

  /// 屏蔽
  case ftBan // = -1

  /// 关注
  case ftFollow // = 1

  /// 好友（互关）
  case ftFriend // = 2

  ///关注加互粉(未用)
  case ftFollowFriend // = 3

  ///自己
  case ftMyself // = 4

  ///粉丝(未用)
  case ftFans // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .ftStranger
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case -1: self = .ftBan
    case 0: self = .ftStranger
    case 1: self = .ftFollow
    case 2: self = .ftFriend
    case 3: self = .ftFollowFriend
    case 4: self = .ftMyself
    case 5: self = .ftFans
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .ftBan: return -1
    case .ftStranger: return 0
    case .ftFollow: return 1
    case .ftFriend: return 2
    case .ftFollowFriend: return 3
    case .ftMyself: return 4
    case .ftFans: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCFriend_FriendType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCFriend_FriendType] = [
    .ftStranger,
    .ftBan,
    .ftFollow,
    .ftFriend,
    .ftFollowFriend,
    .ftMyself,
    .ftFans,
  ]
}

#endif  // swift(>=4.2)

public enum DGCFriend_PrivacySettingOpt: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case uciStatZero // = 0

  /// 所有人
  case uciStatAll // = 1

  /// 相互关注
  case uciStatFriend // = 2

  /// 我关注的
  case uciStatMyFollow // = 3

  /// 拒绝私信
  case uciStatClose // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .uciStatZero
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .uciStatZero
    case 1: self = .uciStatAll
    case 2: self = .uciStatFriend
    case 3: self = .uciStatMyFollow
    case 4: self = .uciStatClose
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .uciStatZero: return 0
    case .uciStatAll: return 1
    case .uciStatFriend: return 2
    case .uciStatMyFollow: return 3
    case .uciStatClose: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCFriend_PrivacySettingOpt: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCFriend_PrivacySettingOpt] = [
    .uciStatZero,
    .uciStatAll,
    .uciStatFriend,
    .uciStatMyFollow,
    .uciStatClose,
  ]
}

#endif  // swift(>=4.2)

public enum DGCFriend_ReplayStatus: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  ///占位不用
  case rsNone // = 0

  ///自由聊天
  case rsAll // = 1

  ///自己没回复过对方
  case rsSelfNoReplay // = 2

  ///对方没回复过自己
  case rsTargetNoReplay // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .rsNone
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .rsNone
    case 1: self = .rsAll
    case 2: self = .rsSelfNoReplay
    case 3: self = .rsTargetNoReplay
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .rsNone: return 0
    case .rsAll: return 1
    case .rsSelfNoReplay: return 2
    case .rsTargetNoReplay: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCFriend_ReplayStatus: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCFriend_ReplayStatus] = [
    .rsNone,
    .rsAll,
    .rsSelfNoReplay,
    .rsTargetNoReplay,
  ]
}

#endif  // swift(>=4.2)

/// cmdid＝ 200301;
public struct DGCFriend_AIChatAnswerNotice {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 忽略AIChatMessage的query字段
  public var message: DGCFriend_AIChatMessage {
    get {return _message ?? DGCFriend_AIChatMessage()}
    set {_message = newValue}
  }
  /// Returns true if `message` has been explicitly set.
  public var hasMessage: Bool {return self._message != nil}
  /// Clears the value of `message`. Subsequent reads from it will return its default value.
  public mutating func clearMessage() {self._message = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _message: DGCFriend_AIChatMessage? = nil
}

public struct DGCFriend_QueryAIChatConfigReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_QueryAIChatConfig {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///AI机器人Id
  public var botID: String = String()

  ///背景图
  public var background: String = String()

  ///简介
  public var intro: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_QueryAIChatConfigRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var config: DGCFriend_QueryAIChatConfig {
    get {return _config ?? DGCFriend_QueryAIChatConfig()}
    set {_config = newValue}
  }
  /// Returns true if `config` has been explicitly set.
  public var hasConfig: Bool {return self._config != nil}
  /// Clears the value of `config`. Subsequent reads from it will return its default value.
  public mutating func clearConfig() {self._config = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _config: DGCFriend_QueryAIChatConfig? = nil
}

public struct DGCFriend_SendAIChatMessageReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// AI机器人Id，由QueryAIChatConfig接口返回
  public var botID: String = String()

  /// 发送的消息文本
  public var text: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_SendAIChatMessageRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_QueryAIChatMessageReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// AI机器人Id，由QueryAIChatConfig接口返回
  public var botID: String = String()

  /// 当前页第一条聊天记录的ID，传空表示最新记录
  public var firstID: String = String()

  /// 一次请求返回多少条聊天记录，默认20 条
  public var limit: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_AIChatMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var query: String = String()

  public var answer: String = String()

  ///时间戳（秒）
  public var createdAt: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_QueryAIChatMessageRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///是否存在下一页
  public var hasMore_p: Bool = false

  public var messages: [DGCFriend_AIChatMessage] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///好友列表
public struct DGCFriend_FriendListReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: DGCFriend_FriendType = .ftStranger

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_FriendListRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var list: [DGCFriend_Friender] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_Friender {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: UInt64 {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  /// [default=FT_STRANGER];
  public var type: Int32 {
    get {return _storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  /// 备注名
  public var alias: String {
    get {return _storage._alias}
    set {_uniqueStorage()._alias = newValue}
  }

  public var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  public var sex: Int32 {
    get {return _storage._sex}
    set {_uniqueStorage()._sex = newValue}
  }

  public var icon: String {
    get {return _storage._icon}
    set {_uniqueStorage()._icon = newValue}
  }

  /// unix time
  public var created: Int64 {
    get {return _storage._created}
    set {_uniqueStorage()._created = newValue}
  }

  /// PlayerFlags
  public var flag: Int64 {
    get {return _storage._flag}
    set {_uniqueStorage()._flag = newValue}
  }

  public var online: Bool {
    get {return _storage._online}
    set {_uniqueStorage()._online = newValue}
  }

  ///操作类型
  public var operType: Int32 {
    get {return _storage._operType}
    set {_uniqueStorage()._operType = newValue}
  }

  ///好友所在房间
  public var roomID: Int32 {
    get {return _storage._roomID}
    set {_uniqueStorage()._roomID = newValue}
  }

  ///签名
  public var signature: String {
    get {return _storage._signature}
    set {_uniqueStorage()._signature = newValue}
  }

  /// 靓号
  public var id2: UInt64 {
    get {return _storage._id2}
    set {_uniqueStorage()._id2 = newValue}
  }

  ///AppId  app_id = 15; // 应用Id
  public var wealthLevel: Int32 {
    get {return _storage._wealthLevel}
    set {_uniqueStorage()._wealthLevel = newValue}
  }

  ///魅力等级
  public var charmLevel: Int32 {
    get {return _storage._charmLevel}
    set {_uniqueStorage()._charmLevel = newValue}
  }

  public var roomName: String {
    get {return _storage._roomName}
    set {_uniqueStorage()._roomName = newValue}
  }

  /// 用户特权
  public var effect: [DGCCommon_Effect] {
    get {return _storage._effect}
    set {_uniqueStorage()._effect = newValue}
  }

  /// 红点标志
  public var redDot: Bool {
    get {return _storage._redDot}
    set {_uniqueStorage()._redDot = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

///关注 屏蔽等操作
public struct DGCFriend_FriendOperReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: UInt64 = 0

  public var oper: DGCFriend_OperType = .none2001

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_FriendOperRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var friend: DGCFriend_Friender {
    get {return _friend ?? DGCFriend_Friender()}
    set {_friend = newValue}
  }
  /// Returns true if `friend` has been explicitly set.
  public var hasFriend: Bool {return self._friend != nil}
  /// Clears the value of `friend`. Subsequent reads from it will return its default value.
  public mutating func clearFriend() {self._friend = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _friend: DGCFriend_Friender? = nil
}

///批量关注 屏蔽等操作
public struct DGCFriend_FriendBatchOperReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var playerID: [Int64] = []

  public var oper: DGCFriend_OperType = .none2001

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_FriendBatchOperRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var friend: [DGCFriend_Friender] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_GetFriendRelReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 玩家Id
  public var playerID: Int64 = 0

  /// 对象Id
  public var targetID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_GetFriendRelRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 好友关系
  public var friendType: DGCFriend_FriendType = .ftStranger

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_FansListReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///请求第一页时传0
  public var index: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_FansListRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///一次最多返回50条记录
  public var list: [DGCFriend_Friender] = []

  ///客户端请求的 index
  public var currentIndex: Int32 = 0

  ///-1代表列表没有下一页了, 否则可以用此值在FansListReq中请求下一页
  public var nextIndex: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///获取关注信息
public struct DGCFriend_FriendIdType {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 好友id
  public var friendID: Int64 = 0

  public var type: DGCFriend_FriendType = .ftStranger

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_CheckFReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var friendID: [Int64] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_CheckFRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var idType: [DGCFriend_FriendIdType] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_UserPrivateSettingReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///1：所有人 2：关注后
  public var optionsSetting: DGCFriend_PrivacySettingOpt = .uciStatZero

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_UserPrivateSettingRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///设置结果
  public var optionsSetting: DGCFriend_PrivacySettingOpt = .uciStatZero

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_QueryPrivateSettingReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///读他人id 可为0
  public var targetPlayerID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_QueryPrivateSettingRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///设置
  public var privateOptions: DGCFriend_PrivacySettingOpt = .uciStatZero

  ///自己的设置
  public var myOptions: DGCFriend_PrivacySettingOpt = .uciStatZero

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_QueryChatReplayReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///聊天对象
  public var toID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_QueryChatReplayRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var replay: DGCFriend_ReplayStatus = .rsNone

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 同步红点数量 200206
public struct DGCFriend_FriendRedDotRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var friendRedDotNum: Int64 = 0

  public var followersRedDotNum: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 客户端主动清除红点
public struct DGCFriend_FriendClearRedDotReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var ftype: DGCFriend_FriendType = .ftStranger

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCFriend_FriendClearRedDotRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension DGCFriend_OperType: @unchecked Sendable {}
extension DGCFriend_FriendType: @unchecked Sendable {}
extension DGCFriend_PrivacySettingOpt: @unchecked Sendable {}
extension DGCFriend_ReplayStatus: @unchecked Sendable {}
extension DGCFriend_AIChatAnswerNotice: @unchecked Sendable {}
extension DGCFriend_QueryAIChatConfigReq: @unchecked Sendable {}
extension DGCFriend_QueryAIChatConfig: @unchecked Sendable {}
extension DGCFriend_QueryAIChatConfigRes: @unchecked Sendable {}
extension DGCFriend_SendAIChatMessageReq: @unchecked Sendable {}
extension DGCFriend_SendAIChatMessageRes: @unchecked Sendable {}
extension DGCFriend_QueryAIChatMessageReq: @unchecked Sendable {}
extension DGCFriend_AIChatMessage: @unchecked Sendable {}
extension DGCFriend_QueryAIChatMessageRes: @unchecked Sendable {}
extension DGCFriend_FriendListReq: @unchecked Sendable {}
extension DGCFriend_FriendListRes: @unchecked Sendable {}
extension DGCFriend_Friender: @unchecked Sendable {}
extension DGCFriend_FriendOperReq: @unchecked Sendable {}
extension DGCFriend_FriendOperRes: @unchecked Sendable {}
extension DGCFriend_FriendBatchOperReq: @unchecked Sendable {}
extension DGCFriend_FriendBatchOperRes: @unchecked Sendable {}
extension DGCFriend_GetFriendRelReq: @unchecked Sendable {}
extension DGCFriend_GetFriendRelRes: @unchecked Sendable {}
extension DGCFriend_FansListReq: @unchecked Sendable {}
extension DGCFriend_FansListRes: @unchecked Sendable {}
extension DGCFriend_FriendIdType: @unchecked Sendable {}
extension DGCFriend_CheckFReq: @unchecked Sendable {}
extension DGCFriend_CheckFRes: @unchecked Sendable {}
extension DGCFriend_UserPrivateSettingReq: @unchecked Sendable {}
extension DGCFriend_UserPrivateSettingRes: @unchecked Sendable {}
extension DGCFriend_QueryPrivateSettingReq: @unchecked Sendable {}
extension DGCFriend_QueryPrivateSettingRes: @unchecked Sendable {}
extension DGCFriend_QueryChatReplayReq: @unchecked Sendable {}
extension DGCFriend_QueryChatReplayRes: @unchecked Sendable {}
extension DGCFriend_FriendRedDotRes: @unchecked Sendable {}
extension DGCFriend_FriendClearRedDotReq: @unchecked Sendable {}
extension DGCFriend_FriendClearRedDotRes: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "friend"

extension DGCFriend_OperType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NONE2001"),
    1: .same(proto: "FOLLOW"),
    2: .same(proto: "UNFOLLOW"),
    3: .same(proto: "BLOCK"),
    4: .same(proto: "UNBLOCK"),
  ]
}

extension DGCFriend_FriendType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    -1: .same(proto: "FT_BAN"),
    0: .same(proto: "FT_STRANGER"),
    1: .same(proto: "FT_FOLLOW"),
    2: .same(proto: "FT_FRIEND"),
    3: .same(proto: "FT_FOLLOW_FRIEND"),
    4: .same(proto: "FT_MYSELF"),
    5: .same(proto: "FT_Fans"),
  ]
}

extension DGCFriend_PrivacySettingOpt: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UCI_STAT_Zero"),
    1: .same(proto: "UCI_STAT_All"),
    2: .same(proto: "UCI_STAT_Friend"),
    3: .same(proto: "UCI_STAT_MyFollow"),
    4: .same(proto: "UCI_STAT_Close"),
  ]
}

extension DGCFriend_ReplayStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "RS_NONE"),
    1: .same(proto: "RS_ALL"),
    2: .same(proto: "RS_SelfNoReplay"),
    3: .same(proto: "RS_TargetNoReplay"),
  ]
}

extension DGCFriend_AIChatAnswerNotice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AIChatAnswerNotice"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "message"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let dgc_v = self._message {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_AIChatAnswerNotice, rhs: DGCFriend_AIChatAnswerNotice) -> Bool {
    if lhs._message != rhs._message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_QueryAIChatConfigReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueryAIChatConfigReq"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_QueryAIChatConfigReq, rhs: DGCFriend_QueryAIChatConfigReq) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_QueryAIChatConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueryAIChatConfig"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "bot_id"),
    2: .same(proto: "background"),
    3: .same(proto: "intro"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.botID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.background) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.intro) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.botID.isEmpty {
      try visitor.visitSingularStringField(value: self.botID, fieldNumber: 1)
    }
    if !self.background.isEmpty {
      try visitor.visitSingularStringField(value: self.background, fieldNumber: 2)
    }
    if !self.intro.isEmpty {
      try visitor.visitSingularStringField(value: self.intro, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_QueryAIChatConfig, rhs: DGCFriend_QueryAIChatConfig) -> Bool {
    if lhs.botID != rhs.botID {return false}
    if lhs.background != rhs.background {return false}
    if lhs.intro != rhs.intro {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_QueryAIChatConfigRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueryAIChatConfigRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "config"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._config) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let dgc_v = self._config {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_QueryAIChatConfigRes, rhs: DGCFriend_QueryAIChatConfigRes) -> Bool {
    if lhs._config != rhs._config {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_SendAIChatMessageReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SendAIChatMessageReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "bot_id"),
    2: .same(proto: "text"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.botID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.text) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.botID.isEmpty {
      try visitor.visitSingularStringField(value: self.botID, fieldNumber: 1)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_SendAIChatMessageReq, rhs: DGCFriend_SendAIChatMessageReq) -> Bool {
    if lhs.botID != rhs.botID {return false}
    if lhs.text != rhs.text {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_SendAIChatMessageRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SendAIChatMessageRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_SendAIChatMessageRes, rhs: DGCFriend_SendAIChatMessageRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_QueryAIChatMessageReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueryAIChatMessageReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "bot_id"),
    2: .standard(proto: "first_id"),
    3: .same(proto: "limit"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.botID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.firstID) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.limit) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.botID.isEmpty {
      try visitor.visitSingularStringField(value: self.botID, fieldNumber: 1)
    }
    if !self.firstID.isEmpty {
      try visitor.visitSingularStringField(value: self.firstID, fieldNumber: 2)
    }
    if self.limit != 0 {
      try visitor.visitSingularInt32Field(value: self.limit, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_QueryAIChatMessageReq, rhs: DGCFriend_QueryAIChatMessageReq) -> Bool {
    if lhs.botID != rhs.botID {return false}
    if lhs.firstID != rhs.firstID {return false}
    if lhs.limit != rhs.limit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_AIChatMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AIChatMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "query"),
    3: .same(proto: "answer"),
    4: .standard(proto: "created_at"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.query) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.answer) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.createdAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.query.isEmpty {
      try visitor.visitSingularStringField(value: self.query, fieldNumber: 2)
    }
    if !self.answer.isEmpty {
      try visitor.visitSingularStringField(value: self.answer, fieldNumber: 3)
    }
    if self.createdAt != 0 {
      try visitor.visitSingularInt64Field(value: self.createdAt, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_AIChatMessage, rhs: DGCFriend_AIChatMessage) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.query != rhs.query {return false}
    if lhs.answer != rhs.answer {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_QueryAIChatMessageRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueryAIChatMessageRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "has_more"),
    2: .same(proto: "messages"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.hasMore_p) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.messages) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.hasMore_p != false {
      try visitor.visitSingularBoolField(value: self.hasMore_p, fieldNumber: 1)
    }
    if !self.messages.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.messages, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_QueryAIChatMessageRes, rhs: DGCFriend_QueryAIChatMessageRes) -> Bool {
    if lhs.hasMore_p != rhs.hasMore_p {return false}
    if lhs.messages != rhs.messages {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FriendListReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FriendListReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != .ftStranger {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FriendListReq, rhs: DGCFriend_FriendListReq) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FriendListRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FriendListRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "list"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.list) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.list.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.list, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FriendListRes, rhs: DGCFriend_FriendListRes) -> Bool {
    if lhs.list != rhs.list {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_Friender: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Friender"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "type"),
    3: .same(proto: "alias"),
    4: .same(proto: "name"),
    5: .same(proto: "sex"),
    6: .same(proto: "icon"),
    8: .same(proto: "created"),
    9: .same(proto: "flag"),
    10: .same(proto: "online"),
    11: .standard(proto: "oper_type"),
    12: .standard(proto: "room_id"),
    13: .same(proto: "signature"),
    14: .same(proto: "id2"),
    16: .standard(proto: "wealth_level"),
    17: .standard(proto: "charm_level"),
    18: .standard(proto: "room_name"),
    19: .same(proto: "effect"),
    20: .standard(proto: "red_dot"),
  ]

  fileprivate class _StorageClass {
    var _id: UInt64 = 0
    var _type: Int32 = 0
    var _alias: String = String()
    var _name: String = String()
    var _sex: Int32 = 0
    var _icon: String = String()
    var _created: Int64 = 0
    var _flag: Int64 = 0
    var _online: Bool = false
    var _operType: Int32 = 0
    var _roomID: Int32 = 0
    var _signature: String = String()
    var _id2: UInt64 = 0
    var _wealthLevel: Int32 = 0
    var _charmLevel: Int32 = 0
    var _roomName: String = String()
    var _effect: [DGCCommon_Effect] = []
    var _redDot: Bool = false

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _type = source._type
      _alias = source._alias
      _name = source._name
      _sex = source._sex
      _icon = source._icon
      _created = source._created
      _flag = source._flag
      _online = source._online
      _operType = source._operType
      _roomID = source._roomID
      _signature = source._signature
      _id2 = source._id2
      _wealthLevel = source._wealthLevel
      _charmLevel = source._charmLevel
      _roomName = source._roomName
      _effect = source._effect
      _redDot = source._redDot
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let dgc_fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch dgc_fieldNumber {
        case 1: try { try decoder.decodeSingularUInt64Field(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularInt32Field(value: &_storage._type) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._alias) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 5: try { try decoder.decodeSingularInt32Field(value: &_storage._sex) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._icon) }()
        case 8: try { try decoder.decodeSingularSInt64Field(value: &_storage._created) }()
        case 9: try { try decoder.decodeSingularSInt64Field(value: &_storage._flag) }()
        case 10: try { try decoder.decodeSingularBoolField(value: &_storage._online) }()
        case 11: try { try decoder.decodeSingularInt32Field(value: &_storage._operType) }()
        case 12: try { try decoder.decodeSingularInt32Field(value: &_storage._roomID) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._signature) }()
        case 14: try { try decoder.decodeSingularUInt64Field(value: &_storage._id2) }()
        case 16: try { try decoder.decodeSingularInt32Field(value: &_storage._wealthLevel) }()
        case 17: try { try decoder.decodeSingularInt32Field(value: &_storage._charmLevel) }()
        case 18: try { try decoder.decodeSingularStringField(value: &_storage._roomName) }()
        case 19: try { try decoder.decodeRepeatedMessageField(value: &_storage._effect) }()
        case 20: try { try decoder.decodeSingularBoolField(value: &_storage._redDot) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._id != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._id, fieldNumber: 1)
      }
      if _storage._type != 0 {
        try visitor.visitSingularInt32Field(value: _storage._type, fieldNumber: 2)
      }
      if !_storage._alias.isEmpty {
        try visitor.visitSingularStringField(value: _storage._alias, fieldNumber: 3)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 4)
      }
      if _storage._sex != 0 {
        try visitor.visitSingularInt32Field(value: _storage._sex, fieldNumber: 5)
      }
      if !_storage._icon.isEmpty {
        try visitor.visitSingularStringField(value: _storage._icon, fieldNumber: 6)
      }
      if _storage._created != 0 {
        try visitor.visitSingularSInt64Field(value: _storage._created, fieldNumber: 8)
      }
      if _storage._flag != 0 {
        try visitor.visitSingularSInt64Field(value: _storage._flag, fieldNumber: 9)
      }
      if _storage._online != false {
        try visitor.visitSingularBoolField(value: _storage._online, fieldNumber: 10)
      }
      if _storage._operType != 0 {
        try visitor.visitSingularInt32Field(value: _storage._operType, fieldNumber: 11)
      }
      if _storage._roomID != 0 {
        try visitor.visitSingularInt32Field(value: _storage._roomID, fieldNumber: 12)
      }
      if !_storage._signature.isEmpty {
        try visitor.visitSingularStringField(value: _storage._signature, fieldNumber: 13)
      }
      if _storage._id2 != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._id2, fieldNumber: 14)
      }
      if _storage._wealthLevel != 0 {
        try visitor.visitSingularInt32Field(value: _storage._wealthLevel, fieldNumber: 16)
      }
      if _storage._charmLevel != 0 {
        try visitor.visitSingularInt32Field(value: _storage._charmLevel, fieldNumber: 17)
      }
      if !_storage._roomName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._roomName, fieldNumber: 18)
      }
      if !_storage._effect.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._effect, fieldNumber: 19)
      }
      if _storage._redDot != false {
        try visitor.visitSingularBoolField(value: _storage._redDot, fieldNumber: 20)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_Friender, rhs: DGCFriend_Friender) -> Bool {
    if lhs.dgc__storage !== rhs.dgc__storage {
      let dgc_storagesAreEqual: Bool = withExtendedLifetime((lhs.dgc__storage, rhs.dgc__storage)) { (_args: (_StorageClass, _StorageClass)) in
        let dgc__storage = _args.0
        let dgc_rhs_storage = _args.1
        if dgc__storage._id != dgc_rhs_storage._id {return false}
        if dgc__storage._type != dgc_rhs_storage._type {return false}
        if dgc__storage._alias != dgc_rhs_storage._alias {return false}
        if dgc__storage._name != dgc_rhs_storage._name {return false}
        if dgc__storage._sex != dgc_rhs_storage._sex {return false}
        if dgc__storage._icon != dgc_rhs_storage._icon {return false}
        if dgc__storage._created != dgc_rhs_storage._created {return false}
        if dgc__storage._flag != dgc_rhs_storage._flag {return false}
        if dgc__storage._online != dgc_rhs_storage._online {return false}
        if dgc__storage._operType != dgc_rhs_storage._operType {return false}
        if dgc__storage._roomID != dgc_rhs_storage._roomID {return false}
        if dgc__storage._signature != dgc_rhs_storage._signature {return false}
        if dgc__storage._id2 != dgc_rhs_storage._id2 {return false}
        if dgc__storage._wealthLevel != dgc_rhs_storage._wealthLevel {return false}
        if dgc__storage._charmLevel != dgc_rhs_storage._charmLevel {return false}
        if dgc__storage._roomName != dgc_rhs_storage._roomName {return false}
        if dgc__storage._effect != dgc_rhs_storage._effect {return false}
        if dgc__storage._redDot != dgc_rhs_storage._redDot {return false}
        return true
      }
      if !dgc_storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FriendOperReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FriendOperReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "oper"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.oper) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularUInt64Field(value: self.id, fieldNumber: 1)
    }
    if self.oper != .none2001 {
      try visitor.visitSingularEnumField(value: self.oper, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FriendOperReq, rhs: DGCFriend_FriendOperReq) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.oper != rhs.oper {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FriendOperRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FriendOperRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "friend"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._friend) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let dgc_v = self._friend {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FriendOperRes, rhs: DGCFriend_FriendOperRes) -> Bool {
    if lhs._friend != rhs._friend {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FriendBatchOperReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FriendBatchOperReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "player_id"),
    2: .same(proto: "oper"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedInt64Field(value: &self.playerID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.oper) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.playerID.isEmpty {
      try visitor.visitPackedInt64Field(value: self.playerID, fieldNumber: 1)
    }
    if self.oper != .none2001 {
      try visitor.visitSingularEnumField(value: self.oper, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FriendBatchOperReq, rhs: DGCFriend_FriendBatchOperReq) -> Bool {
    if lhs.playerID != rhs.playerID {return false}
    if lhs.oper != rhs.oper {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FriendBatchOperRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FriendBatchOperRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "friend"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.friend) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.friend.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.friend, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FriendBatchOperRes, rhs: DGCFriend_FriendBatchOperRes) -> Bool {
    if lhs.friend != rhs.friend {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_GetFriendRelReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetFriendRelReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "player_id"),
    2: .standard(proto: "target_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.playerID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.targetID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.playerID != 0 {
      try visitor.visitSingularInt64Field(value: self.playerID, fieldNumber: 1)
    }
    if self.targetID != 0 {
      try visitor.visitSingularInt64Field(value: self.targetID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_GetFriendRelReq, rhs: DGCFriend_GetFriendRelReq) -> Bool {
    if lhs.playerID != rhs.playerID {return false}
    if lhs.targetID != rhs.targetID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_GetFriendRelRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetFriendRelRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "friend_type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.friendType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.friendType != .ftStranger {
      try visitor.visitSingularEnumField(value: self.friendType, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_GetFriendRelRes, rhs: DGCFriend_GetFriendRelRes) -> Bool {
    if lhs.friendType != rhs.friendType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FansListReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FansListReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "index"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.index) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.index != 0 {
      try visitor.visitSingularInt32Field(value: self.index, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FansListReq, rhs: DGCFriend_FansListReq) -> Bool {
    if lhs.index != rhs.index {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FansListRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FansListRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "list"),
    2: .standard(proto: "current_index"),
    3: .standard(proto: "next_index"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.list) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.currentIndex) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.nextIndex) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.list.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.list, fieldNumber: 1)
    }
    if self.currentIndex != 0 {
      try visitor.visitSingularInt32Field(value: self.currentIndex, fieldNumber: 2)
    }
    if self.nextIndex != 0 {
      try visitor.visitSingularInt32Field(value: self.nextIndex, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FansListRes, rhs: DGCFriend_FansListRes) -> Bool {
    if lhs.list != rhs.list {return false}
    if lhs.currentIndex != rhs.currentIndex {return false}
    if lhs.nextIndex != rhs.nextIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FriendIdType: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FriendIdType"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "friendId"),
    2: .same(proto: "type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.friendID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.friendID != 0 {
      try visitor.visitSingularInt64Field(value: self.friendID, fieldNumber: 1)
    }
    if self.type != .ftStranger {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FriendIdType, rhs: DGCFriend_FriendIdType) -> Bool {
    if lhs.friendID != rhs.friendID {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_CheckFReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CheckFReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "friendId"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedInt64Field(value: &self.friendID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.friendID.isEmpty {
      try visitor.visitPackedInt64Field(value: self.friendID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_CheckFReq, rhs: DGCFriend_CheckFReq) -> Bool {
    if lhs.friendID != rhs.friendID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_CheckFRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CheckFRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "idType"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.idType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.idType.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.idType, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_CheckFRes, rhs: DGCFriend_CheckFRes) -> Bool {
    if lhs.idType != rhs.idType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_UserPrivateSettingReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UserPrivateSettingReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "options_setting"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.optionsSetting) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.optionsSetting != .uciStatZero {
      try visitor.visitSingularEnumField(value: self.optionsSetting, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_UserPrivateSettingReq, rhs: DGCFriend_UserPrivateSettingReq) -> Bool {
    if lhs.optionsSetting != rhs.optionsSetting {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_UserPrivateSettingRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UserPrivateSettingRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "options_setting"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.optionsSetting) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.optionsSetting != .uciStatZero {
      try visitor.visitSingularEnumField(value: self.optionsSetting, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_UserPrivateSettingRes, rhs: DGCFriend_UserPrivateSettingRes) -> Bool {
    if lhs.optionsSetting != rhs.optionsSetting {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_QueryPrivateSettingReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueryPrivateSettingReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "target_playerId"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt64Field(value: &self.targetPlayerID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.targetPlayerID != 0 {
      try visitor.visitSingularSInt64Field(value: self.targetPlayerID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_QueryPrivateSettingReq, rhs: DGCFriend_QueryPrivateSettingReq) -> Bool {
    if lhs.targetPlayerID != rhs.targetPlayerID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_QueryPrivateSettingRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueryPrivateSettingRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "private_options"),
    2: .standard(proto: "my_options"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.privateOptions) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.myOptions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.privateOptions != .uciStatZero {
      try visitor.visitSingularEnumField(value: self.privateOptions, fieldNumber: 1)
    }
    if self.myOptions != .uciStatZero {
      try visitor.visitSingularEnumField(value: self.myOptions, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_QueryPrivateSettingRes, rhs: DGCFriend_QueryPrivateSettingRes) -> Bool {
    if lhs.privateOptions != rhs.privateOptions {return false}
    if lhs.myOptions != rhs.myOptions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_QueryChatReplayReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueryChatReplayReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "toId"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.toID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.toID != 0 {
      try visitor.visitSingularInt64Field(value: self.toID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_QueryChatReplayReq, rhs: DGCFriend_QueryChatReplayReq) -> Bool {
    if lhs.toID != rhs.toID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_QueryChatReplayRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QueryChatReplayRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "replay"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.replay) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.replay != .rsNone {
      try visitor.visitSingularEnumField(value: self.replay, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_QueryChatReplayRes, rhs: DGCFriend_QueryChatReplayRes) -> Bool {
    if lhs.replay != rhs.replay {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FriendRedDotRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FriendRedDotRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "friendRedDotNum"),
    2: .same(proto: "followersRedDotNum"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.friendRedDotNum) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.followersRedDotNum) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.friendRedDotNum != 0 {
      try visitor.visitSingularInt64Field(value: self.friendRedDotNum, fieldNumber: 1)
    }
    if self.followersRedDotNum != 0 {
      try visitor.visitSingularInt64Field(value: self.followersRedDotNum, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FriendRedDotRes, rhs: DGCFriend_FriendRedDotRes) -> Bool {
    if lhs.friendRedDotNum != rhs.friendRedDotNum {return false}
    if lhs.followersRedDotNum != rhs.followersRedDotNum {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FriendClearRedDotReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FriendClearRedDotReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "ftype"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.ftype) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.ftype != .ftStranger {
      try visitor.visitSingularEnumField(value: self.ftype, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FriendClearRedDotReq, rhs: DGCFriend_FriendClearRedDotReq) -> Bool {
    if lhs.ftype != rhs.ftype {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCFriend_FriendClearRedDotRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FriendClearRedDotRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCFriend_FriendClearRedDotRes, rhs: DGCFriend_FriendClearRedDotRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
