// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: lanuch.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct DGCLanuch_GetFutureSplashAdsReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var playerID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLanuch_GetFutureSplashAdsRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var currentSplashAds: DGCLanuch_GetFutureSplashAdsRes.DGCSplashAdsRes {
    get {return _currentSplashAds ?? DGCLanuch_GetFutureSplashAdsRes.DGCSplashAdsRes()}
    set {_currentSplashAds = newValue}
  }
  /// Returns true if `currentSplashAds` has been explicitly set.
  public var hasCurrentSplashAds: Bool {return self._currentSplashAds != nil}
  /// Clears the value of `currentSplashAds`. Subsequent reads from it will return its default value.
  public mutating func clearCurrentSplashAds() {self._currentSplashAds = nil}

  /// 需要缓存资源的地址
  public var cacheUrls: [String] = []

  /// 主题
  public var topic: [DGCLanuch_GetFutureSplashAdsRes.DGCAppTopic] = []

  /// 生日特权(提前3天返回)
  public var birthdayPrivilege: DGCLanuch_GetFutureSplashAdsRes.DGCBirthdayPrivilege {
    get {return _birthdayPrivilege ?? DGCLanuch_GetFutureSplashAdsRes.DGCBirthdayPrivilege()}
    set {_birthdayPrivilege = newValue}
  }
  /// Returns true if `birthdayPrivilege` has been explicitly set.
  public var hasBirthdayPrivilege: Bool {return self._birthdayPrivilege != nil}
  /// Clears the value of `birthdayPrivilege`. Subsequent reads from it will return its default value.
  public mutating func clearBirthdayPrivilege() {self._birthdayPrivilege = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct DGCSplashAdsRes {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// 开屏广告ID，上报需要
    public var splashAdsID: Int32 = 0

    /// 开屏广告资源地址，如果未缓存，则不用播放，有缓存才播放
    public var splashAdsURL: String = String()

    /// 开屏广告秒数
    public var advtTcSec: Int32 = 0

    /// 跳转模式代码：0=不跳转 1=跳转房间 2=跳转URL
    public var fowardModeCode: String = String()

    /// 跳转资源。跳转房间时为房间ID，跳转URL时为URL的完整地址
    public var fowardRes: String = String()

    /// 广告名称，用于上报计数
    public var splashAdsName: String = String()

    /// 结束时间
    public var endTime: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct DGCAppTopic {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// id
    public var id: Int32 = 0

    /// 主题名
    public var topic: String = String()

    /// 主题资源链接
    public var url: String = String()

    /// 开始时间戳（单位秒）
    public var start: Int64 = 0

    /// 结束时间戳（单位秒）
    public var end: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct DGCBirthdayPrivilege {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var nickname: String = String()

    public var icon: String = String()

    /// 背景资源
    public var bg: String = String()

    /// 生日时间戳
    public var birthday: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}

  fileprivate var _currentSplashAds: DGCLanuch_GetFutureSplashAdsRes.DGCSplashAdsRes? = nil
  fileprivate var _birthdayPrivilege: DGCLanuch_GetFutureSplashAdsRes.DGCBirthdayPrivilege? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension DGCLanuch_GetFutureSplashAdsReq: @unchecked Sendable {}
extension DGCLanuch_GetFutureSplashAdsRes: @unchecked Sendable {}
extension DGCLanuch_GetFutureSplashAdsRes.DGCSplashAdsRes: @unchecked Sendable {}
extension DGCLanuch_GetFutureSplashAdsRes.DGCAppTopic: @unchecked Sendable {}
extension DGCLanuch_GetFutureSplashAdsRes.DGCBirthdayPrivilege: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "lanuch"

extension DGCLanuch_GetFutureSplashAdsReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetFutureSplashAdsReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "player_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.playerID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.playerID != 0 {
      try visitor.visitSingularInt64Field(value: self.playerID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLanuch_GetFutureSplashAdsReq, rhs: DGCLanuch_GetFutureSplashAdsReq) -> Bool {
    if lhs.playerID != rhs.playerID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLanuch_GetFutureSplashAdsRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetFutureSplashAdsRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "currentSplashAds"),
    2: .same(proto: "cacheUrls"),
    3: .same(proto: "topic"),
    4: .same(proto: "birthdayPrivilege"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._currentSplashAds) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.cacheUrls) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.topic) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._birthdayPrivilege) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let dgc_v = self._currentSplashAds {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 1)
    } }()
    if !self.cacheUrls.isEmpty {
      try visitor.visitRepeatedStringField(value: self.cacheUrls, fieldNumber: 2)
    }
    if !self.topic.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.topic, fieldNumber: 3)
    }
    try { if let dgc_v = self._birthdayPrivilege {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLanuch_GetFutureSplashAdsRes, rhs: DGCLanuch_GetFutureSplashAdsRes) -> Bool {
    if lhs._currentSplashAds != rhs._currentSplashAds {return false}
    if lhs.cacheUrls != rhs.cacheUrls {return false}
    if lhs.topic != rhs.topic {return false}
    if lhs._birthdayPrivilege != rhs._birthdayPrivilege {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLanuch_GetFutureSplashAdsRes.DGCSplashAdsRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = DGCLanuch_GetFutureSplashAdsRes.protoMessageName + ".DGCSplashAdsRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "splashAdsId"),
    2: .same(proto: "splashAdsUrl"),
    3: .same(proto: "advtTcSec"),
    4: .same(proto: "fowardModeCode"),
    5: .same(proto: "fowardRes"),
    6: .same(proto: "splashAdsName"),
    7: .same(proto: "endTime"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.splashAdsID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.splashAdsURL) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.advtTcSec) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.fowardModeCode) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.fowardRes) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.splashAdsName) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.endTime) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.splashAdsID != 0 {
      try visitor.visitSingularInt32Field(value: self.splashAdsID, fieldNumber: 1)
    }
    if !self.splashAdsURL.isEmpty {
      try visitor.visitSingularStringField(value: self.splashAdsURL, fieldNumber: 2)
    }
    if self.advtTcSec != 0 {
      try visitor.visitSingularInt32Field(value: self.advtTcSec, fieldNumber: 3)
    }
    if !self.fowardModeCode.isEmpty {
      try visitor.visitSingularStringField(value: self.fowardModeCode, fieldNumber: 4)
    }
    if !self.fowardRes.isEmpty {
      try visitor.visitSingularStringField(value: self.fowardRes, fieldNumber: 5)
    }
    if !self.splashAdsName.isEmpty {
      try visitor.visitSingularStringField(value: self.splashAdsName, fieldNumber: 6)
    }
    if self.endTime != 0 {
      try visitor.visitSingularInt64Field(value: self.endTime, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLanuch_GetFutureSplashAdsRes.DGCSplashAdsRes, rhs: DGCLanuch_GetFutureSplashAdsRes.DGCSplashAdsRes) -> Bool {
    if lhs.splashAdsID != rhs.splashAdsID {return false}
    if lhs.splashAdsURL != rhs.splashAdsURL {return false}
    if lhs.advtTcSec != rhs.advtTcSec {return false}
    if lhs.fowardModeCode != rhs.fowardModeCode {return false}
    if lhs.fowardRes != rhs.fowardRes {return false}
    if lhs.splashAdsName != rhs.splashAdsName {return false}
    if lhs.endTime != rhs.endTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLanuch_GetFutureSplashAdsRes.DGCAppTopic: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = DGCLanuch_GetFutureSplashAdsRes.protoMessageName + ".DGCAppTopic"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "topic"),
    3: .same(proto: "url"),
    4: .same(proto: "start"),
    5: .same(proto: "end"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.topic) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.start) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.end) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt32Field(value: self.id, fieldNumber: 1)
    }
    if !self.topic.isEmpty {
      try visitor.visitSingularStringField(value: self.topic, fieldNumber: 2)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 3)
    }
    if self.start != 0 {
      try visitor.visitSingularInt64Field(value: self.start, fieldNumber: 4)
    }
    if self.end != 0 {
      try visitor.visitSingularInt64Field(value: self.end, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLanuch_GetFutureSplashAdsRes.DGCAppTopic, rhs: DGCLanuch_GetFutureSplashAdsRes.DGCAppTopic) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.topic != rhs.topic {return false}
    if lhs.url != rhs.url {return false}
    if lhs.start != rhs.start {return false}
    if lhs.end != rhs.end {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLanuch_GetFutureSplashAdsRes.DGCBirthdayPrivilege: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = DGCLanuch_GetFutureSplashAdsRes.protoMessageName + ".DGCBirthdayPrivilege"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "nickname"),
    2: .same(proto: "icon"),
    3: .same(proto: "bg"),
    4: .same(proto: "birthday"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.nickname) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.icon) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.bg) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.birthday) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.nickname.isEmpty {
      try visitor.visitSingularStringField(value: self.nickname, fieldNumber: 1)
    }
    if !self.icon.isEmpty {
      try visitor.visitSingularStringField(value: self.icon, fieldNumber: 2)
    }
    if !self.bg.isEmpty {
      try visitor.visitSingularStringField(value: self.bg, fieldNumber: 3)
    }
    if self.birthday != 0 {
      try visitor.visitSingularInt64Field(value: self.birthday, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLanuch_GetFutureSplashAdsRes.DGCBirthdayPrivilege, rhs: DGCLanuch_GetFutureSplashAdsRes.DGCBirthdayPrivilege) -> Bool {
    if lhs.nickname != rhs.nickname {return false}
    if lhs.icon != rhs.icon {return false}
    if lhs.bg != rhs.bg {return false}
    if lhs.birthday != rhs.birthday {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
