// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: search.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct DGCSearch_SearchPlayersReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 页数
  public var page: Int32 = 0

  /// 每页多少条数据 (有cache，pageSize不要随便变！）
  public var pageSize: Int32 = 0

  /// 搜索关键词，房间Id或用户Id或公会Id以及房间名等
  public var keyWord: String = String()

  ///是否搜索房间，否=搜索ID和用户，是=搜索房间名
  public var ifRoom: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCSearch_SearchPlayersRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 页数
  public var page: Int32 = 0

  /// 每页多少条数据
  public var pageSize: Int32 = 0

  public var list: [DGCSearch_SearchPlayerEntry] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 搜索条目
public struct DGCSearch_SearchPlayerEntry {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Int64 = 0

  /// 靓号. ==0时没有
  public var id2: Int64 = 0

  public var nickname: String = String()

  public var sex: DGCCommon_SexType = .unknown

  /// 图标
  public var icon: String = String()

  /// sint64 charm = 6;
  /// sint32 charm_level = 7; // 魅力等级
  /// sint64 wealth = 8; // 财富值
  /// sint32 wealthl_evel = 9; // 财富等级
  public var online: Bool = false

  ///用户当前所在房间
  public var roomID: Int64 = 0

  /// bool has_passwd = 13; //用户在线并身处某房间时，标识该房间是否有密码,true为有密码，false为没有密码
  /// string room_name = 14; //房间名称
  /// string room_image = 15; //房间封面
  public var effect: [DGCCommon_Effect] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension DGCSearch_SearchPlayersReq: @unchecked Sendable {}
extension DGCSearch_SearchPlayersRes: @unchecked Sendable {}
extension DGCSearch_SearchPlayerEntry: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "search"

extension DGCSearch_SearchPlayersReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SearchPlayersReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "page"),
    2: .same(proto: "pageSize"),
    3: .standard(proto: "key_word"),
    4: .standard(proto: "if_room"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt32Field(value: &self.page) }()
      case 2: try { try decoder.decodeSingularSInt32Field(value: &self.pageSize) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.keyWord) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.ifRoom) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.page != 0 {
      try visitor.visitSingularSInt32Field(value: self.page, fieldNumber: 1)
    }
    if self.pageSize != 0 {
      try visitor.visitSingularSInt32Field(value: self.pageSize, fieldNumber: 2)
    }
    if !self.keyWord.isEmpty {
      try visitor.visitSingularStringField(value: self.keyWord, fieldNumber: 3)
    }
    if self.ifRoom != false {
      try visitor.visitSingularBoolField(value: self.ifRoom, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCSearch_SearchPlayersReq, rhs: DGCSearch_SearchPlayersReq) -> Bool {
    if lhs.page != rhs.page {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.keyWord != rhs.keyWord {return false}
    if lhs.ifRoom != rhs.ifRoom {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCSearch_SearchPlayersRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SearchPlayersRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "page"),
    2: .same(proto: "pageSize"),
    3: .same(proto: "list"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt32Field(value: &self.page) }()
      case 2: try { try decoder.decodeSingularSInt32Field(value: &self.pageSize) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.list) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.page != 0 {
      try visitor.visitSingularSInt32Field(value: self.page, fieldNumber: 1)
    }
    if self.pageSize != 0 {
      try visitor.visitSingularSInt32Field(value: self.pageSize, fieldNumber: 2)
    }
    if !self.list.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.list, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCSearch_SearchPlayersRes, rhs: DGCSearch_SearchPlayersRes) -> Bool {
    if lhs.page != rhs.page {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.list != rhs.list {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCSearch_SearchPlayerEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SearchPlayerEntry"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "id2"),
    3: .same(proto: "nickname"),
    4: .same(proto: "sex"),
    5: .same(proto: "icon"),
    10: .same(proto: "online"),
    11: .standard(proto: "room_id"),
    16: .same(proto: "effect"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularSInt64Field(value: &self.id2) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.nickname) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.sex) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.icon) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self.online) }()
      case 11: try { try decoder.decodeSingularSInt64Field(value: &self.roomID) }()
      case 16: try { try decoder.decodeRepeatedMessageField(value: &self.effect) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularSInt64Field(value: self.id, fieldNumber: 1)
    }
    if self.id2 != 0 {
      try visitor.visitSingularSInt64Field(value: self.id2, fieldNumber: 2)
    }
    if !self.nickname.isEmpty {
      try visitor.visitSingularStringField(value: self.nickname, fieldNumber: 3)
    }
    if self.sex != .unknown {
      try visitor.visitSingularEnumField(value: self.sex, fieldNumber: 4)
    }
    if !self.icon.isEmpty {
      try visitor.visitSingularStringField(value: self.icon, fieldNumber: 5)
    }
    if self.online != false {
      try visitor.visitSingularBoolField(value: self.online, fieldNumber: 10)
    }
    if self.roomID != 0 {
      try visitor.visitSingularSInt64Field(value: self.roomID, fieldNumber: 11)
    }
    if !self.effect.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.effect, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCSearch_SearchPlayerEntry, rhs: DGCSearch_SearchPlayerEntry) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.id2 != rhs.id2 {return false}
    if lhs.nickname != rhs.nickname {return false}
    if lhs.sex != rhs.sex {return false}
    if lhs.icon != rhs.icon {return false}
    if lhs.online != rhs.online {return false}
    if lhs.roomID != rhs.roomID {return false}
    if lhs.effect != rhs.effect {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
