// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tars_rpc_v2.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct DGCProto_MSGInput {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///  具体函数方法
  public var alias: String = String()

  ///  进入房间需要带上key=subscribe-room-push value = roomId 退出房间 value = -1
  public var opt: Dictionary<String,String> = [:]

  ///  请求数据包
  public var req: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCProto_MSGOutput {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 返回值
  public var ret: Int32 = 0

  /// 上下文
  public var opt: Dictionary<String,String> = [:]

  /// 返回数据包
  public var rsp: Data = Data()

  /// 错误信息
  public var desc: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///服务器推送消息
public struct DGCProto_ServerPushMsg {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var cmdID: Int32 = 0

  public var body: Data = Data()

  public var opt: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension DGCProto_MSGInput: @unchecked Sendable {}
extension DGCProto_MSGOutput: @unchecked Sendable {}
extension DGCProto_ServerPushMsg: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proto"

extension DGCProto_MSGInput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MSGInput"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "alias"),
    2: .same(proto: "opt"),
    3: .same(proto: "req"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.alias) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.opt) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.req) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.alias.isEmpty {
      try visitor.visitSingularStringField(value: self.alias, fieldNumber: 1)
    }
    if !self.opt.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.opt, fieldNumber: 2)
    }
    if !self.req.isEmpty {
      try visitor.visitSingularBytesField(value: self.req, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCProto_MSGInput, rhs: DGCProto_MSGInput) -> Bool {
    if lhs.alias != rhs.alias {return false}
    if lhs.opt != rhs.opt {return false}
    if lhs.req != rhs.req {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCProto_MSGOutput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MSGOutput"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "ret"),
    2: .same(proto: "opt"),
    3: .same(proto: "rsp"),
    4: .same(proto: "desc"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.ret) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.opt) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.rsp) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.desc) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.ret != 0 {
      try visitor.visitSingularInt32Field(value: self.ret, fieldNumber: 1)
    }
    if !self.opt.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.opt, fieldNumber: 2)
    }
    if !self.rsp.isEmpty {
      try visitor.visitSingularBytesField(value: self.rsp, fieldNumber: 3)
    }
    if !self.desc.isEmpty {
      try visitor.visitSingularStringField(value: self.desc, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCProto_MSGOutput, rhs: DGCProto_MSGOutput) -> Bool {
    if lhs.ret != rhs.ret {return false}
    if lhs.opt != rhs.opt {return false}
    if lhs.rsp != rhs.rsp {return false}
    if lhs.desc != rhs.desc {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCProto_ServerPushMsg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ServerPushMsg"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "cmdId"),
    2: .same(proto: "body"),
    3: .same(proto: "opt"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.cmdID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.body) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.opt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.cmdID != 0 {
      try visitor.visitSingularInt32Field(value: self.cmdID, fieldNumber: 1)
    }
    if !self.body.isEmpty {
      try visitor.visitSingularBytesField(value: self.body, fieldNumber: 2)
    }
    if !self.opt.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.opt, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCProto_ServerPushMsg, rhs: DGCProto_ServerPushMsg) -> Bool {
    if lhs.cmdID != rhs.cmdID {return false}
    if lhs.body != rhs.body {return false}
    if lhs.opt != rhs.opt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
