// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: im.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

///获取用户的验证sig
public struct DGCIM_UserSigReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCIM_UserSigRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sig: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///  系统邮件
public struct DGCIM_MailMsg {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// mail id
  public var id: Int64 = 0

  /// 广播的cmdId
  public var cmdID: Int32 = 0

  /// 创建时间
  public var createAt: Int32 = 0

  /// 根据cmdId，创建对应的结构体
  public var data: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// last_read_time值由前端保存在本地，last_read_time更新机制：
/// 1、登录时判断对应的last_read_time>1分钟才请求，请求返回后更新last_read_time为当前时间
/// 2、收到对应cmdId时，更新last_read_time为当前时间
/// 当前对应的cmdId消息有：101001(SystemMsgNotice系统消息), 100137(BroadcastMateMatchMsg交友成功系统消息)
public struct DGCIM_ReadMailReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 最后读取时间
  public var lastReadTime: Int32 = 0

  /// 消息归属。0-系统消息，1-活动消息
  public var msgBelong: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCIM_ReadMailRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var list: [DGCIM_MailMsg] = []

  /// 过期消息id
  public var msgID: [Int64] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCIM_LastMailReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 最后读取时间
  public var lastReadTime: Int32 = 0

  /// 消息归属。0-系统消息，1-活动消息
  public var msgBelong: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCIM_LastMailRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 是否成功
  public var flag: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCIM_UnReadMailReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 消息归属。0-系统消息，1-活动消息
  public var msgBelong: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCIM_UnReadMailRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unreadCount: Int32 = 0

  public var lastMailText: String = String()

  public var lastSendTime: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///系统消息通知 CmdId=101001  CmdId=101002  CmdId=101003 CmdId=101012 CmdId=101023
public struct DGCIM_SystemMsgNotice {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///信息标题
  public var msgTitle: String = String()

  ///发送内容
  public var msg: String = String()

  ///图片路径
  public var picture: String = String()

  /// 发送时间
  public var sendTime: UInt32 = 0

  ///跳转描述
  public var linkText: String = String()

  ///内部路由跳转地址
  public var routerURL: String = String()

  ///房间id
  public var roomID: Data = Data()

  ///消息状态 1.未发送 2.已发送 3.未发送已过期 4.已发送已过期
  public var status: UInt32 = 0

  ///过期时间
  public var overdueTime: Int64 = 0

  ///消息类型
  public var msgType: UInt32 = 0

  ///消息条件
  public var condition: String = String()

  ///消息归属。0-系统消息，1-活动消息。默认是系统消息
  public var msgBelong: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 广播新邮件 cmdId=101005, 更新last_read_time为当前时间
public struct DGCIM_BroadcastMailMsg {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mail: DGCIM_MailMsg {
    get {return _mail ?? DGCIM_MailMsg()}
    set {_mail = newValue}
  }
  /// Returns true if `mail` has been explicitly set.
  public var hasMail: Bool {return self._mail != nil}
  /// Clears the value of `mail`. Subsequent reads from it will return its default value.
  public mutating func clearMail() {self._mail = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _mail: DGCIM_MailMsg? = nil
}

///立即过期撤回广播邮件 过期系统消息Id列表
public struct DGCIM_OverdueMsgNotice {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 过期消息id
  public var msgID: [Int64] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension DGCIM_UserSigReq: @unchecked Sendable {}
extension DGCIM_UserSigRes: @unchecked Sendable {}
extension DGCIM_MailMsg: @unchecked Sendable {}
extension DGCIM_ReadMailReq: @unchecked Sendable {}
extension DGCIM_ReadMailRes: @unchecked Sendable {}
extension DGCIM_LastMailReq: @unchecked Sendable {}
extension DGCIM_LastMailRes: @unchecked Sendable {}
extension DGCIM_UnReadMailReq: @unchecked Sendable {}
extension DGCIM_UnReadMailRes: @unchecked Sendable {}
extension DGCIM_SystemMsgNotice: @unchecked Sendable {}
extension DGCIM_BroadcastMailMsg: @unchecked Sendable {}
extension DGCIM_OverdueMsgNotice: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "IM"

extension DGCIM_UserSigReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UserSigReq"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_UserSigReq, rhs: DGCIM_UserSigReq) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCIM_UserSigRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UserSigRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "sig"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sig) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sig.isEmpty {
      try visitor.visitSingularStringField(value: self.sig, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_UserSigRes, rhs: DGCIM_UserSigRes) -> Bool {
    if lhs.sig != rhs.sig {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCIM_MailMsg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MailMsg"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .standard(proto: "cmd_id"),
    3: .standard(proto: "create_at"),
    4: .same(proto: "data"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.cmdID) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.createAt) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if self.cmdID != 0 {
      try visitor.visitSingularInt32Field(value: self.cmdID, fieldNumber: 2)
    }
    if self.createAt != 0 {
      try visitor.visitSingularInt32Field(value: self.createAt, fieldNumber: 3)
    }
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_MailMsg, rhs: DGCIM_MailMsg) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.cmdID != rhs.cmdID {return false}
    if lhs.createAt != rhs.createAt {return false}
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCIM_ReadMailReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReadMailReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "last_read_time"),
    2: .standard(proto: "msg_belong"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.lastReadTime) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.msgBelong) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.lastReadTime != 0 {
      try visitor.visitSingularInt32Field(value: self.lastReadTime, fieldNumber: 1)
    }
    if self.msgBelong != 0 {
      try visitor.visitSingularUInt32Field(value: self.msgBelong, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_ReadMailReq, rhs: DGCIM_ReadMailReq) -> Bool {
    if lhs.lastReadTime != rhs.lastReadTime {return false}
    if lhs.msgBelong != rhs.msgBelong {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCIM_ReadMailRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReadMailRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "list"),
    2: .standard(proto: "msg_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.list) }()
      case 2: try { try decoder.decodeRepeatedInt64Field(value: &self.msgID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.list.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.list, fieldNumber: 1)
    }
    if !self.msgID.isEmpty {
      try visitor.visitPackedInt64Field(value: self.msgID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_ReadMailRes, rhs: DGCIM_ReadMailRes) -> Bool {
    if lhs.list != rhs.list {return false}
    if lhs.msgID != rhs.msgID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCIM_LastMailReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LastMailReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "last_read_time"),
    2: .standard(proto: "msg_belong"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.lastReadTime) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.msgBelong) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.lastReadTime != 0 {
      try visitor.visitSingularInt32Field(value: self.lastReadTime, fieldNumber: 1)
    }
    if self.msgBelong != 0 {
      try visitor.visitSingularUInt32Field(value: self.msgBelong, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_LastMailReq, rhs: DGCIM_LastMailReq) -> Bool {
    if lhs.lastReadTime != rhs.lastReadTime {return false}
    if lhs.msgBelong != rhs.msgBelong {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCIM_LastMailRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LastMailRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "flag"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.flag) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.flag != false {
      try visitor.visitSingularBoolField(value: self.flag, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_LastMailRes, rhs: DGCIM_LastMailRes) -> Bool {
    if lhs.flag != rhs.flag {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCIM_UnReadMailReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UnReadMailReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .standard(proto: "msg_belong"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.msgBelong) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.msgBelong != 0 {
      try visitor.visitSingularUInt32Field(value: self.msgBelong, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_UnReadMailReq, rhs: DGCIM_UnReadMailReq) -> Bool {
    if lhs.msgBelong != rhs.msgBelong {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCIM_UnReadMailRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UnReadMailRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "unread_count"),
    2: .standard(proto: "last_mail_text"),
    3: .standard(proto: "last_send_time"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.unreadCount) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.lastMailText) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.lastSendTime) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.unreadCount != 0 {
      try visitor.visitSingularInt32Field(value: self.unreadCount, fieldNumber: 1)
    }
    if !self.lastMailText.isEmpty {
      try visitor.visitSingularStringField(value: self.lastMailText, fieldNumber: 2)
    }
    if !self.lastSendTime.isEmpty {
      try visitor.visitSingularStringField(value: self.lastSendTime, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_UnReadMailRes, rhs: DGCIM_UnReadMailRes) -> Bool {
    if lhs.unreadCount != rhs.unreadCount {return false}
    if lhs.lastMailText != rhs.lastMailText {return false}
    if lhs.lastSendTime != rhs.lastSendTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCIM_SystemMsgNotice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SystemMsgNotice"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "msg_title"),
    2: .same(proto: "msg"),
    3: .same(proto: "picture"),
    4: .standard(proto: "send_time"),
    5: .standard(proto: "link_text"),
    6: .standard(proto: "router_url"),
    7: .standard(proto: "room_id"),
    8: .same(proto: "status"),
    9: .standard(proto: "overdue_time"),
    10: .standard(proto: "msg_type"),
    11: .same(proto: "condition"),
    12: .standard(proto: "msg_belong"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.msgTitle) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.msg) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.picture) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.sendTime) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.linkText) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.routerURL) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.roomID) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.status) }()
      case 9: try { try decoder.decodeSingularInt64Field(value: &self.overdueTime) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.msgType) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.condition) }()
      case 12: try { try decoder.decodeSingularUInt32Field(value: &self.msgBelong) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.msgTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.msgTitle, fieldNumber: 1)
    }
    if !self.msg.isEmpty {
      try visitor.visitSingularStringField(value: self.msg, fieldNumber: 2)
    }
    if !self.picture.isEmpty {
      try visitor.visitSingularStringField(value: self.picture, fieldNumber: 3)
    }
    if self.sendTime != 0 {
      try visitor.visitSingularUInt32Field(value: self.sendTime, fieldNumber: 4)
    }
    if !self.linkText.isEmpty {
      try visitor.visitSingularStringField(value: self.linkText, fieldNumber: 5)
    }
    if !self.routerURL.isEmpty {
      try visitor.visitSingularStringField(value: self.routerURL, fieldNumber: 6)
    }
    if !self.roomID.isEmpty {
      try visitor.visitSingularBytesField(value: self.roomID, fieldNumber: 7)
    }
    if self.status != 0 {
      try visitor.visitSingularUInt32Field(value: self.status, fieldNumber: 8)
    }
    if self.overdueTime != 0 {
      try visitor.visitSingularInt64Field(value: self.overdueTime, fieldNumber: 9)
    }
    if self.msgType != 0 {
      try visitor.visitSingularUInt32Field(value: self.msgType, fieldNumber: 10)
    }
    if !self.condition.isEmpty {
      try visitor.visitSingularStringField(value: self.condition, fieldNumber: 11)
    }
    if self.msgBelong != 0 {
      try visitor.visitSingularUInt32Field(value: self.msgBelong, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_SystemMsgNotice, rhs: DGCIM_SystemMsgNotice) -> Bool {
    if lhs.msgTitle != rhs.msgTitle {return false}
    if lhs.msg != rhs.msg {return false}
    if lhs.picture != rhs.picture {return false}
    if lhs.sendTime != rhs.sendTime {return false}
    if lhs.linkText != rhs.linkText {return false}
    if lhs.routerURL != rhs.routerURL {return false}
    if lhs.roomID != rhs.roomID {return false}
    if lhs.status != rhs.status {return false}
    if lhs.overdueTime != rhs.overdueTime {return false}
    if lhs.msgType != rhs.msgType {return false}
    if lhs.condition != rhs.condition {return false}
    if lhs.msgBelong != rhs.msgBelong {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCIM_BroadcastMailMsg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastMailMsg"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "mail"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._mail) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let dgc_v = self._mail {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_BroadcastMailMsg, rhs: DGCIM_BroadcastMailMsg) -> Bool {
    if lhs._mail != rhs._mail {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCIM_OverdueMsgNotice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OverdueMsgNotice"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "msg_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedInt64Field(value: &self.msgID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.msgID.isEmpty {
      try visitor.visitPackedInt64Field(value: self.msgID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCIM_OverdueMsgNotice, rhs: DGCIM_OverdueMsgNotice) -> Bool {
    if lhs.msgID != rhs.msgID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
