// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pay.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// 内购配置
public struct DGCPay_RechargeIap {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///平台 ios google
  public var platform: String = String()

  ///内购产品id
  public var productID: String = String()

  ///充值金额
  public var money: Float = 0

  ///包名
  public var packageName: String = String()

  ///名称或说明
  public var name: String = String()

  ///充值的金币数
  public var gold: Int32 = 0

  ///额外加送金币
  public var extGold: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 获取内购列表
public struct DGCPay_IapListReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///包名
  public var packageName: String = String()

  ///平台 ios google
  public var platform: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPay_IapListRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 内购配置
  public var confRechargeIapList: [DGCPay_RechargeIap] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 创建订单
public struct DGCPay_CreateOrderReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var packageName: String = String()

  public var productID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPay_CreateOrderRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var orderID: String = String()

  /// 是否限制了充值
  public var isLimited: Bool = false

  /// 通知
  public var notice: DGCPay_CreateOrderRes.DGCNotice {
    get {return _notice ?? DGCPay_CreateOrderRes.DGCNotice()}
    set {_notice = newValue}
  }
  /// Returns true if `notice` has been explicitly set.
  public var hasNotice: Bool {return self._notice != nil}
  /// Clears the value of `notice`. Subsequent reads from it will return its default value.
  public mutating func clearNotice() {self._notice = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct DGCNotice {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// 弹窗标题
    public var title: String = String()

    /// 弹窗内容
    public var content: String = String()

    /// 跳转链接(比如：wh://open?dynamic=300&path=(room?id=10006698)）
    public var url: String = String()

    /// 按钮上的文案
    public var buttonStr: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}

  fileprivate var _notice: DGCPay_CreateOrderRes.DGCNotice? = nil
}

public struct DGCPay_VerifyIAPReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///交易id
  public var transactionID: String = String()

  ///账号
  public var accountID: Int64 = 0

  ///订单号，可能为空，如果为空后台则找到
  public var orderNo: String = String()

  ///票据
  public var receipt: String = String()

  ///包名
  public var packageName: String = String()

  ///订单ID是否来自苹果回调：false：程序内存中 true：苹果回调中
  public var orderSource: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPay_VerifyIAPRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var money: [Float] = []

  public var currency: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 金钱资产
public struct DGCPay_AssetsMoneyReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPay_AssetsMoney {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///金币
  public var gold: Int32 = 0

  ///   uint32 silver = 2;            //银币，暂时没有用
  public var giftTicket: UInt32 = 0

  ///累计金额
  public var charge: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 金钱资产返回
public struct DGCPay_AssetsMoneyRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///1请求返回，2推送
  public var flag: UInt32 = 0

  public var money: DGCPay_AssetsMoney {
    get {return _money ?? DGCPay_AssetsMoney()}
    set {_money = newValue}
  }
  /// Returns true if `money` has been explicitly set.
  public var hasMoney: Bool {return self._money != nil}
  /// Clears the value of `money`. Subsequent reads from it will return its default value.
  public mutating func clearMoney() {self._money = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _money: DGCPay_AssetsMoney? = nil
}

public struct DGCPay_TicketChangCoinReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var diamond: Int32 = 0

  public var passwd: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// errCode 33024 钻石不足; 33029 提现密码不正确; 33018 失败;
public struct DGCPay_TicketChangCoinRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension DGCPay_RechargeIap: @unchecked Sendable {}
extension DGCPay_IapListReq: @unchecked Sendable {}
extension DGCPay_IapListRes: @unchecked Sendable {}
extension DGCPay_CreateOrderReq: @unchecked Sendable {}
extension DGCPay_CreateOrderRes: @unchecked Sendable {}
extension DGCPay_CreateOrderRes.DGCNotice: @unchecked Sendable {}
extension DGCPay_VerifyIAPReq: @unchecked Sendable {}
extension DGCPay_VerifyIAPRes: @unchecked Sendable {}
extension DGCPay_AssetsMoneyReq: @unchecked Sendable {}
extension DGCPay_AssetsMoney: @unchecked Sendable {}
extension DGCPay_AssetsMoneyRes: @unchecked Sendable {}
extension DGCPay_TicketChangCoinReq: @unchecked Sendable {}
extension DGCPay_TicketChangCoinRes: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pay"

extension DGCPay_RechargeIap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RechargeIap"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    3: .same(proto: "platform"),
    1: .standard(proto: "product_id"),
    5: .same(proto: "money"),
    2: .standard(proto: "package_name"),
    4: .same(proto: "name"),
    6: .same(proto: "gold"),
    7: .standard(proto: "ext_gold"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.productID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.packageName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.money) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.gold) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.extGold) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.productID.isEmpty {
      try visitor.visitSingularStringField(value: self.productID, fieldNumber: 1)
    }
    if !self.packageName.isEmpty {
      try visitor.visitSingularStringField(value: self.packageName, fieldNumber: 2)
    }
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 3)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 4)
    }
    if self.money != 0 {
      try visitor.visitSingularFloatField(value: self.money, fieldNumber: 5)
    }
    if self.gold != 0 {
      try visitor.visitSingularInt32Field(value: self.gold, fieldNumber: 6)
    }
    if self.extGold != 0 {
      try visitor.visitSingularInt32Field(value: self.extGold, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_RechargeIap, rhs: DGCPay_RechargeIap) -> Bool {
    if lhs.platform != rhs.platform {return false}
    if lhs.productID != rhs.productID {return false}
    if lhs.money != rhs.money {return false}
    if lhs.packageName != rhs.packageName {return false}
    if lhs.name != rhs.name {return false}
    if lhs.gold != rhs.gold {return false}
    if lhs.extGold != rhs.extGold {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_IapListReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IapListReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "package_name"),
    2: .same(proto: "platform"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.packageName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.packageName.isEmpty {
      try visitor.visitSingularStringField(value: self.packageName, fieldNumber: 1)
    }
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_IapListReq, rhs: DGCPay_IapListReq) -> Bool {
    if lhs.packageName != rhs.packageName {return false}
    if lhs.platform != rhs.platform {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_IapListRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IapListRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "conf_recharge_iap_list"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.confRechargeIapList) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.confRechargeIapList.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.confRechargeIapList, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_IapListRes, rhs: DGCPay_IapListRes) -> Bool {
    if lhs.confRechargeIapList != rhs.confRechargeIapList {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_CreateOrderReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CreateOrderReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "package_name"),
    2: .standard(proto: "product_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.packageName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.productID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.packageName.isEmpty {
      try visitor.visitSingularStringField(value: self.packageName, fieldNumber: 1)
    }
    if !self.productID.isEmpty {
      try visitor.visitSingularStringField(value: self.productID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_CreateOrderReq, rhs: DGCPay_CreateOrderReq) -> Bool {
    if lhs.packageName != rhs.packageName {return false}
    if lhs.productID != rhs.productID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_CreateOrderRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CreateOrderRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "order_id"),
    2: .standard(proto: "is_limited"),
    3: .same(proto: "notice"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.orderID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isLimited) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._notice) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.orderID.isEmpty {
      try visitor.visitSingularStringField(value: self.orderID, fieldNumber: 1)
    }
    if self.isLimited != false {
      try visitor.visitSingularBoolField(value: self.isLimited, fieldNumber: 2)
    }
    try { if let dgc_v = self._notice {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_CreateOrderRes, rhs: DGCPay_CreateOrderRes) -> Bool {
    if lhs.orderID != rhs.orderID {return false}
    if lhs.isLimited != rhs.isLimited {return false}
    if lhs._notice != rhs._notice {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_CreateOrderRes.DGCNotice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = DGCPay_CreateOrderRes.protoMessageName + ".DGCNotice"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "title"),
    2: .same(proto: "content"),
    3: .same(proto: "url"),
    4: .standard(proto: "button_str"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.content) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.buttonStr) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 1)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 2)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 3)
    }
    if !self.buttonStr.isEmpty {
      try visitor.visitSingularStringField(value: self.buttonStr, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_CreateOrderRes.DGCNotice, rhs: DGCPay_CreateOrderRes.DGCNotice) -> Bool {
    if lhs.title != rhs.title {return false}
    if lhs.content != rhs.content {return false}
    if lhs.url != rhs.url {return false}
    if lhs.buttonStr != rhs.buttonStr {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_VerifyIAPReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VerifyIAPReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    3: .same(proto: "transactionId"),
    1: .same(proto: "accountId"),
    4: .standard(proto: "order_no"),
    2: .same(proto: "receipt"),
    5: .standard(proto: "package_name"),
    6: .standard(proto: "order_source"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.accountID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.receipt) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.transactionID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.orderNo) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.packageName) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.orderSource) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.accountID != 0 {
      try visitor.visitSingularInt64Field(value: self.accountID, fieldNumber: 1)
    }
    if !self.receipt.isEmpty {
      try visitor.visitSingularStringField(value: self.receipt, fieldNumber: 2)
    }
    if !self.transactionID.isEmpty {
      try visitor.visitSingularStringField(value: self.transactionID, fieldNumber: 3)
    }
    if !self.orderNo.isEmpty {
      try visitor.visitSingularStringField(value: self.orderNo, fieldNumber: 4)
    }
    if !self.packageName.isEmpty {
      try visitor.visitSingularStringField(value: self.packageName, fieldNumber: 5)
    }
    if self.orderSource != false {
      try visitor.visitSingularBoolField(value: self.orderSource, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_VerifyIAPReq, rhs: DGCPay_VerifyIAPReq) -> Bool {
    if lhs.transactionID != rhs.transactionID {return false}
    if lhs.accountID != rhs.accountID {return false}
    if lhs.orderNo != rhs.orderNo {return false}
    if lhs.receipt != rhs.receipt {return false}
    if lhs.packageName != rhs.packageName {return false}
    if lhs.orderSource != rhs.orderSource {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_VerifyIAPRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VerifyIAPRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "money"),
    2: .same(proto: "currency"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedFloatField(value: &self.money) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.currency) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.money.isEmpty {
      try visitor.visitPackedFloatField(value: self.money, fieldNumber: 1)
    }
    if !self.currency.isEmpty {
      try visitor.visitSingularStringField(value: self.currency, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_VerifyIAPRes, rhs: DGCPay_VerifyIAPRes) -> Bool {
    if lhs.money != rhs.money {return false}
    if lhs.currency != rhs.currency {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_AssetsMoneyReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AssetsMoneyReq"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_AssetsMoneyReq, rhs: DGCPay_AssetsMoneyReq) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_AssetsMoney: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AssetsMoney"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "gold"),
    3: .standard(proto: "gift_ticket"),
    4: .same(proto: "charge"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.gold) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.giftTicket) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.charge) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.gold != 0 {
      try visitor.visitSingularInt32Field(value: self.gold, fieldNumber: 1)
    }
    if self.giftTicket != 0 {
      try visitor.visitSingularUInt32Field(value: self.giftTicket, fieldNumber: 3)
    }
    if self.charge != 0 {
      try visitor.visitSingularUInt32Field(value: self.charge, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_AssetsMoney, rhs: DGCPay_AssetsMoney) -> Bool {
    if lhs.gold != rhs.gold {return false}
    if lhs.giftTicket != rhs.giftTicket {return false}
    if lhs.charge != rhs.charge {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_AssetsMoneyRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AssetsMoneyRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "flag"),
    2: .same(proto: "money"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.flag) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._money) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.flag != 0 {
      try visitor.visitSingularUInt32Field(value: self.flag, fieldNumber: 1)
    }
    try { if let dgc_v = self._money {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_AssetsMoneyRes, rhs: DGCPay_AssetsMoneyRes) -> Bool {
    if lhs.flag != rhs.flag {return false}
    if lhs._money != rhs._money {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_TicketChangCoinReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TicketChangCoinReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "diamond"),
    2: .same(proto: "passwd"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt32Field(value: &self.diamond) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.passwd) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.diamond != 0 {
      try visitor.visitSingularSInt32Field(value: self.diamond, fieldNumber: 1)
    }
    if !self.passwd.isEmpty {
      try visitor.visitSingularStringField(value: self.passwd, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_TicketChangCoinReq, rhs: DGCPay_TicketChangCoinReq) -> Bool {
    if lhs.diamond != rhs.diamond {return false}
    if lhs.passwd != rhs.passwd {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPay_TicketChangCoinRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TicketChangCoinRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPay_TicketChangCoinRes, rhs: DGCPay_TicketChangCoinRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
