// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: login.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum DGCLogin_UauthLoginType: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case ltDev // = 0

  /// 短信登录
  case ltSms // = 4

  /// apple
  case ltApple // = 6

  /// id密码登录
  case ltNative // = 1

  /// facebook
  case ltFacebook // = 7
  case ltQq // = 2

  /// 一键登录
  case ltQuick // = 5
  case ltWeixin // = 3

  /// 手机密码登录
  case ltPhonePassword // = 8

  /// 谷歌
  case ltGoogle // = 9

  /// snapchat
  case ltSnapchat // = 10
  case UNRECOGNIZED(Int)

  public init() {
    self = .ltDev
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .ltDev
    case 1: self = .ltNative
    case 2: self = .ltQq
    case 3: self = .ltWeixin
    case 4: self = .ltSms
    case 5: self = .ltQuick
    case 6: self = .ltApple
    case 7: self = .ltFacebook
    case 8: self = .ltPhonePassword
    case 9: self = .ltGoogle
    case 10: self = .ltSnapchat
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .ltDev: return 0
    case .ltNative: return 1
    case .ltQq: return 2
    case .ltWeixin: return 3
    case .ltSms: return 4
    case .ltQuick: return 5
    case .ltApple: return 6
    case .ltFacebook: return 7
    case .ltPhonePassword: return 8
    case .ltGoogle: return 9
    case .ltSnapchat: return 10
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCLogin_UauthLoginType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCLogin_UauthLoginType] = [
    .ltDev,
    .ltSms,
    .ltApple,
    .ltNative,
    .ltFacebook,
    .ltQq,
    .ltQuick,
    .ltWeixin,
    .ltPhonePassword,
    .ltGoogle,
    .ltSnapchat,
  ]
}

#endif  // swift(>=4.2)

/// 与 GetSmsCodeReq_Action 相同，以这个为主
public enum DGCLogin_SmsAction: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// 默认是登录
  case login // = 0
  case bindPhone // = 1
  case changePhone // = 2

  /// 设置工资兑换金币密码
  case setExchangePw // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .login
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .login
    case 1: self = .bindPhone
    case 2: self = .changePhone
    case 3: self = .setExchangePw
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .login: return 0
    case .bindPhone: return 1
    case .changePhone: return 2
    case .setExchangePw: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension DGCLogin_SmsAction: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCLogin_SmsAction] = [
    .login,
    .bindPhone,
    .changePhone,
    .setExchangePw,
  ]
}

#endif  // swift(>=4.2)

/// 统一第三方登录
public struct DGCLogin_ThirdLoginReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 苹果登录类型identity_token
  public var identityToken: String = String()

  /// 设备号
  public var deviceID: String = String()

  /// eg：微信访问code
  public var code: String = String()

  /// 渠道号
  public var channel: Int32 = 0

  public var accessToken: String = String()

  public var appID: String = String()

  /// 读取 common.ext.proto中的DeviceType
  public var deviceType: Int32 = 0

  /// 苹果登录类型identity_token
  public var authorizationCode: String = String()

  /// 登录类型
  public var loginType: DGCLogin_UauthLoginType = .ltDev

  /// // 苹果登录类型作为nickname
  public var fullName: String = String()

  public var afInfoMap: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///统一第三方登录
public struct DGCLogin_ThirdLoginRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 透传登录类型
  public var loginType: DGCLogin_UauthLoginType = .ltDev

  /// 号码是否注册过
  public var isRegister: Bool = false

  /// 如果已经注册则登录，并返回登录结果
  public var login: DGCLogin_CommonSignInRes {
    get {return _login ?? DGCLogin_CommonSignInRes()}
    set {_login = newValue}
  }
  /// Returns true if `login` has been explicitly set.
  public var hasLogin: Bool {return self._login != nil}
  /// Clears the value of `login`. Subsequent reads from it will return its default value.
  public mutating func clearLogin() {self._login = nil}

  /// 返回登录类型透传的第三方值，qq/wx UnionId，未注册用户走统一第三方注册
  public var value: String = String()

  /// 是否需要拉取手机绑定的账号列表 true: 需要 false: 不需要
  public var needPullPhoneBindAccount: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _login: DGCLogin_CommonSignInRes? = nil
}

/// 通用登录结果返回
public struct DGCLogin_CommonSignInRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// login token
  public var loginToken: String = String()

  public var userID: Int64 = 0

  /// 是否新账号
  public var isNew: Bool = false

  /// 扩展字段
  public var extends: Dictionary<String,String> = [:]

  /// 登录类型
  public var loginType: DGCLogin_UauthLoginType = .ltDev

  /// 是否需要拉取手机绑定的账号列表 true: 需要 false: 不需要
  public var needPullPhoneBindAccount: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 帐号安全检验 是否绑定手机 和设置密码
public struct DGCLogin_CheckAccountSecurityReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_CheckAccountSecurityResp {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 是否已设置密码
  public var setPassword: Bool = false

  /// 绑定的手机号，如果没有返回空字符串
  public var bindPhone: String = String()

  /// 是否显示设置兑换金币密码入口
  public var showExchangePw: Bool = false

  /// 是否已设置兑换金币密码
  public var setExchangePw: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// apple登录
public struct DGCLogin_SignInWithAppleReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 作为nickname
  public var fullName: String = String()

  public var identityToken: String = String()

  public var authorizationCode: String = String()

  ///设备号
  public var deviceID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// id或手机密码登录
public struct DGCLogin_IdOrPhoneLoginReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var password: String = String()

  /// 国家区号
  public var country: Int32 = 0

  /// id或手机
  public var value: String = String()

  /// 登录签名(废弃了，现在用MD5不需要）
  public var sign: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_UpdateBindPhoneReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 新手机号
  public var phone: String = String()

  /// 验证码
  public var code: String = String()

  /// 国家码
  public var country: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_UpdateBindPhoneResp {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_VerifyExchangePasswordReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var password: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_VerifyExchangePasswordResp {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var code: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_SetExchangePasswordReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var firstInput: String = String()

  public var secondInput: String = String()

  /// 忘记密码，此时不和原密码校验
  public var forget: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_SetExchangePasswordResp {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_VerifySmsCodeReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var action: DGCLogin_SmsAction = .login

  public var code: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_VerifySmsCodeResp {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 获取短信
public struct DGCLogin_GetSmsCodeReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 手机号
  public var phone: String = String()

  /// 国家区号
  public var country: Int32 = 0

  /// 是否是第三方注册时候获手机验证码
  public var isBind: Bool = false

  /// 区分发短信类型，默认是登录
  public var action: DGCLogin_GetSmsCodeReq.DGCAction = .login

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum DGCAction: SwiftProtobuf.Enum {
    public typealias RawValue = Int

    /// 默认是登录
    case login // = 0
    case bindPhone // = 1
    case changePhone // = 2

    /// 设置工资兑换金币密码
    case etExchangePw // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .login
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .login
      case 1: self = .bindPhone
      case 2: self = .changePhone
      case 3: self = .etExchangePw
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .login: return 0
      case .bindPhone: return 1
      case .changePhone: return 2
      case .etExchangePw: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}
}

#if swift(>=4.2)

extension DGCLogin_GetSmsCodeReq.DGCAction: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [DGCLogin_GetSmsCodeReq.DGCAction] = [
    .login,
    .bindPhone,
    .changePhone,
    .etExchangePw,
  ]
}

#endif  // swift(>=4.2)

public struct DGCLogin_GetSmsCodeRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 号码是否注册过
  public var isRegister: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 手机短信登录, 当是没有注册的手机时会自动创建
public struct DGCLogin_LoginWithPhoneSMSReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 设备号
  public var deviceID: String = String()

  /// 国家区号
  public var country: Int32 = 0

  /// 读取 common.ext.proto中的DeviceType
  public var deviceType: DGCCommon_DeviceType = .dtUnknown

  /// 手机号
  public var phone: String = String()

  /// (不再使用，直接使用sms_code) GetSmsTokenReq接口获取
  public var smsToken: String = String()

  /// 渠道号
  public var channel: Int32 = 0

  /// 当不为空时，合并GetSmsTokenReq的请求
  public var smsCode: String = String()

  /// 当出现换设备登录出错时,带上此参数
  public var accountID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_LogoutReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// sessionKey
  public var key: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_LogoutRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 登录
public struct DGCLogin_LoginReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var key: String = String()

  public var deviceType: DGCCommon_DeviceType = .dtUnknown

  public var deviceID: String = String()

  /// 推送token
  public var pushToken: String = String()

  ///国家代码
  public var countryCode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_LoginRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var accountID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_DeleteAccountConfirmReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 验证码
  public var code: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_DeleteAccountConfirmRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 保存天数
  public var keepDays: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_ZoneCountry {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///英文名，用于获取国家图标
  public var countryEn: String = String()

  ///显示的国家名称（国际化后的文本）
  public var countryName: String = String()

  ///国家区号
  public var countryPhone: Int64 = 0

  ///排序
  public var position: Int32 = 0

  ///国家代码
  public var countryCode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_GetUserZoneReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCLogin_GetUserZoneRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///用户IP对应国家的序号，如果返回-1，表示用户不在可使用的区域内，用于优选（默认选择）国家
  public var defaultIndex: Int32 = 0

  ///用户IP区域的国家信息
  public var country: [DGCLogin_ZoneCountry] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 通知设备上线
public struct DGCLogin_BroadcastRelogin {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: String = String()

  public var deviceType: DGCCommon_DeviceType = .dtUnknown

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension DGCLogin_UauthLoginType: @unchecked Sendable {}
extension DGCLogin_SmsAction: @unchecked Sendable {}
extension DGCLogin_ThirdLoginReq: @unchecked Sendable {}
extension DGCLogin_ThirdLoginRes: @unchecked Sendable {}
extension DGCLogin_CommonSignInRes: @unchecked Sendable {}
extension DGCLogin_CheckAccountSecurityReq: @unchecked Sendable {}
extension DGCLogin_CheckAccountSecurityResp: @unchecked Sendable {}
extension DGCLogin_SignInWithAppleReq: @unchecked Sendable {}
extension DGCLogin_IdOrPhoneLoginReq: @unchecked Sendable {}
extension DGCLogin_UpdateBindPhoneReq: @unchecked Sendable {}
extension DGCLogin_UpdateBindPhoneResp: @unchecked Sendable {}
extension DGCLogin_VerifyExchangePasswordReq: @unchecked Sendable {}
extension DGCLogin_VerifyExchangePasswordResp: @unchecked Sendable {}
extension DGCLogin_SetExchangePasswordReq: @unchecked Sendable {}
extension DGCLogin_SetExchangePasswordResp: @unchecked Sendable {}
extension DGCLogin_VerifySmsCodeReq: @unchecked Sendable {}
extension DGCLogin_VerifySmsCodeResp: @unchecked Sendable {}
extension DGCLogin_GetSmsCodeReq: @unchecked Sendable {}
extension DGCLogin_GetSmsCodeReq.DGCAction: @unchecked Sendable {}
extension DGCLogin_GetSmsCodeRes: @unchecked Sendable {}
extension DGCLogin_LoginWithPhoneSMSReq: @unchecked Sendable {}
extension DGCLogin_LogoutReq: @unchecked Sendable {}
extension DGCLogin_LogoutRes: @unchecked Sendable {}
extension DGCLogin_LoginReq: @unchecked Sendable {}
extension DGCLogin_LoginRes: @unchecked Sendable {}
extension DGCLogin_DeleteAccountConfirmReq: @unchecked Sendable {}
extension DGCLogin_DeleteAccountConfirmRes: @unchecked Sendable {}
extension DGCLogin_ZoneCountry: @unchecked Sendable {}
extension DGCLogin_GetUserZoneReq: @unchecked Sendable {}
extension DGCLogin_GetUserZoneRes: @unchecked Sendable {}
extension DGCLogin_BroadcastRelogin: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "login"

extension DGCLogin_UauthLoginType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "LT_DEV"),
    1: .same(proto: "LT_NATIVE"),
    2: .same(proto: "LT_QQ"),
    3: .same(proto: "LT_WEIXIN"),
    4: .same(proto: "LT_SMS"),
    5: .same(proto: "LT_QUICK"),
    6: .same(proto: "LT_APPLE"),
    7: .same(proto: "LT_FACEBOOK"),
    8: .same(proto: "LT_PHONE_PASSWORD"),
    9: .same(proto: "LT_GOOGLE"),
    10: .same(proto: "LT_SNAPCHAT"),
  ]
}

extension DGCLogin_SmsAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "Login"),
    1: .same(proto: "BindPhone"),
    2: .same(proto: "ChangePhone"),
    3: .same(proto: "SetExchangePW"),
  ]
}

extension DGCLogin_ThirdLoginReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ThirdLoginReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    8: .standard(proto: "identity_token"),
    4: .standard(proto: "device_id"),
    1: .same(proto: "code"),
    6: .same(proto: "channel"),
    2: .standard(proto: "access_token"),
    3: .standard(proto: "app_id"),
    5: .standard(proto: "device_type"),
    9: .standard(proto: "authorization_code"),
    7: .standard(proto: "login_type"),
    10: .standard(proto: "full_name"),
    11: .same(proto: "afInfoMap"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.accessToken) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.appID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.deviceType) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.channel) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.loginType) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.identityToken) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.authorizationCode) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.fullName) }()
      case 11: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.afInfoMap) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 1)
    }
    if !self.accessToken.isEmpty {
      try visitor.visitSingularStringField(value: self.accessToken, fieldNumber: 2)
    }
    if !self.appID.isEmpty {
      try visitor.visitSingularStringField(value: self.appID, fieldNumber: 3)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 4)
    }
    if self.deviceType != 0 {
      try visitor.visitSingularInt32Field(value: self.deviceType, fieldNumber: 5)
    }
    if self.channel != 0 {
      try visitor.visitSingularInt32Field(value: self.channel, fieldNumber: 6)
    }
    if self.loginType != .ltDev {
      try visitor.visitSingularEnumField(value: self.loginType, fieldNumber: 7)
    }
    if !self.identityToken.isEmpty {
      try visitor.visitSingularStringField(value: self.identityToken, fieldNumber: 8)
    }
    if !self.authorizationCode.isEmpty {
      try visitor.visitSingularStringField(value: self.authorizationCode, fieldNumber: 9)
    }
    if !self.fullName.isEmpty {
      try visitor.visitSingularStringField(value: self.fullName, fieldNumber: 10)
    }
    if !self.afInfoMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.afInfoMap, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_ThirdLoginReq, rhs: DGCLogin_ThirdLoginReq) -> Bool {
    if lhs.identityToken != rhs.identityToken {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.code != rhs.code {return false}
    if lhs.channel != rhs.channel {return false}
    if lhs.accessToken != rhs.accessToken {return false}
    if lhs.appID != rhs.appID {return false}
    if lhs.deviceType != rhs.deviceType {return false}
    if lhs.authorizationCode != rhs.authorizationCode {return false}
    if lhs.loginType != rhs.loginType {return false}
    if lhs.fullName != rhs.fullName {return false}
    if lhs.afInfoMap != rhs.afInfoMap {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_ThirdLoginRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ThirdLoginRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    3: .standard(proto: "login_type"),
    1: .standard(proto: "is_register"),
    2: .same(proto: "login"),
    4: .same(proto: "value"),
    5: .standard(proto: "need_pull_phone_bind_account"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isRegister) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._login) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.loginType) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.value) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.needPullPhoneBindAccount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.isRegister != false {
      try visitor.visitSingularBoolField(value: self.isRegister, fieldNumber: 1)
    }
    try { if let dgc_v = self._login {
      try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 2)
    } }()
    if self.loginType != .ltDev {
      try visitor.visitSingularEnumField(value: self.loginType, fieldNumber: 3)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 4)
    }
    if self.needPullPhoneBindAccount != false {
      try visitor.visitSingularBoolField(value: self.needPullPhoneBindAccount, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_ThirdLoginRes, rhs: DGCLogin_ThirdLoginRes) -> Bool {
    if lhs.loginType != rhs.loginType {return false}
    if lhs.isRegister != rhs.isRegister {return false}
    if lhs._login != rhs._login {return false}
    if lhs.value != rhs.value {return false}
    if lhs.needPullPhoneBindAccount != rhs.needPullPhoneBindAccount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_CommonSignInRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommonSignInRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "login_token"),
    3: .standard(proto: "user_id"),
    2: .standard(proto: "is_new"),
    4: .same(proto: "extends"),
    5: .standard(proto: "login_type"),
    6: .standard(proto: "need_pull_phone_bind_account"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.loginToken) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isNew) }()
      case 3: try { try decoder.decodeSingularSInt64Field(value: &self.userID) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.extends) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.loginType) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.needPullPhoneBindAccount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.loginToken.isEmpty {
      try visitor.visitSingularStringField(value: self.loginToken, fieldNumber: 1)
    }
    if self.isNew != false {
      try visitor.visitSingularBoolField(value: self.isNew, fieldNumber: 2)
    }
    if self.userID != 0 {
      try visitor.visitSingularSInt64Field(value: self.userID, fieldNumber: 3)
    }
    if !self.extends.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.extends, fieldNumber: 4)
    }
    if self.loginType != .ltDev {
      try visitor.visitSingularEnumField(value: self.loginType, fieldNumber: 5)
    }
    if self.needPullPhoneBindAccount != false {
      try visitor.visitSingularBoolField(value: self.needPullPhoneBindAccount, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_CommonSignInRes, rhs: DGCLogin_CommonSignInRes) -> Bool {
    if lhs.loginToken != rhs.loginToken {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.isNew != rhs.isNew {return false}
    if lhs.extends != rhs.extends {return false}
    if lhs.loginType != rhs.loginType {return false}
    if lhs.needPullPhoneBindAccount != rhs.needPullPhoneBindAccount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_CheckAccountSecurityReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CheckAccountSecurityReq"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_CheckAccountSecurityReq, rhs: DGCLogin_CheckAccountSecurityReq) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_CheckAccountSecurityResp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CheckAccountSecurityResp"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "set_password"),
    2: .standard(proto: "bind_phone"),
    3: .standard(proto: "show_exchange_pw"),
    4: .standard(proto: "set_exchange_pw"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.setPassword) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.bindPhone) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.showExchangePw) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.setExchangePw) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.setPassword != false {
      try visitor.visitSingularBoolField(value: self.setPassword, fieldNumber: 1)
    }
    if !self.bindPhone.isEmpty {
      try visitor.visitSingularStringField(value: self.bindPhone, fieldNumber: 2)
    }
    if self.showExchangePw != false {
      try visitor.visitSingularBoolField(value: self.showExchangePw, fieldNumber: 3)
    }
    if self.setExchangePw != false {
      try visitor.visitSingularBoolField(value: self.setExchangePw, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_CheckAccountSecurityResp, rhs: DGCLogin_CheckAccountSecurityResp) -> Bool {
    if lhs.setPassword != rhs.setPassword {return false}
    if lhs.bindPhone != rhs.bindPhone {return false}
    if lhs.showExchangePw != rhs.showExchangePw {return false}
    if lhs.setExchangePw != rhs.setExchangePw {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_SignInWithAppleReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SignInWithAppleReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    3: .standard(proto: "full_name"),
    1: .standard(proto: "identity_token"),
    2: .standard(proto: "authorization_code"),
    4: .standard(proto: "device_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.identityToken) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.authorizationCode) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.fullName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.identityToken.isEmpty {
      try visitor.visitSingularStringField(value: self.identityToken, fieldNumber: 1)
    }
    if !self.authorizationCode.isEmpty {
      try visitor.visitSingularStringField(value: self.authorizationCode, fieldNumber: 2)
    }
    if !self.fullName.isEmpty {
      try visitor.visitSingularStringField(value: self.fullName, fieldNumber: 3)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_SignInWithAppleReq, rhs: DGCLogin_SignInWithAppleReq) -> Bool {
    if lhs.fullName != rhs.fullName {return false}
    if lhs.identityToken != rhs.identityToken {return false}
    if lhs.authorizationCode != rhs.authorizationCode {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_IdOrPhoneLoginReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IdOrPhoneLoginReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    3: .same(proto: "password"),
    1: .same(proto: "country"),
    2: .same(proto: "value"),
    4: .same(proto: "sign"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.country) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.value) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.password) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.sign) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.country != 0 {
      try visitor.visitSingularInt32Field(value: self.country, fieldNumber: 1)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 2)
    }
    if !self.password.isEmpty {
      try visitor.visitSingularStringField(value: self.password, fieldNumber: 3)
    }
    if !self.sign.isEmpty {
      try visitor.visitSingularStringField(value: self.sign, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_IdOrPhoneLoginReq, rhs: DGCLogin_IdOrPhoneLoginReq) -> Bool {
    if lhs.password != rhs.password {return false}
    if lhs.country != rhs.country {return false}
    if lhs.value != rhs.value {return false}
    if lhs.sign != rhs.sign {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_UpdateBindPhoneReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateBindPhoneReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "phone"),
    2: .same(proto: "code"),
    3: .same(proto: "country"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.phone) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.country) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.phone.isEmpty {
      try visitor.visitSingularStringField(value: self.phone, fieldNumber: 1)
    }
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 2)
    }
    if self.country != 0 {
      try visitor.visitSingularInt32Field(value: self.country, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_UpdateBindPhoneReq, rhs: DGCLogin_UpdateBindPhoneReq) -> Bool {
    if lhs.phone != rhs.phone {return false}
    if lhs.code != rhs.code {return false}
    if lhs.country != rhs.country {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_UpdateBindPhoneResp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateBindPhoneResp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_UpdateBindPhoneResp, rhs: DGCLogin_UpdateBindPhoneResp) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_VerifyExchangePasswordReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VerifyExchangePasswordReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "password"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.password) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.password.isEmpty {
      try visitor.visitSingularStringField(value: self.password, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_VerifyExchangePasswordReq, rhs: DGCLogin_VerifyExchangePasswordReq) -> Bool {
    if lhs.password != rhs.password {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_VerifyExchangePasswordResp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VerifyExchangePasswordResp"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "code"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.code) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != 0 {
      try visitor.visitSingularInt32Field(value: self.code, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_VerifyExchangePasswordResp, rhs: DGCLogin_VerifyExchangePasswordResp) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_SetExchangePasswordReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetExchangePasswordReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "first_input"),
    2: .standard(proto: "second_input"),
    3: .same(proto: "forget"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.firstInput) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.secondInput) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.forget) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.firstInput.isEmpty {
      try visitor.visitSingularStringField(value: self.firstInput, fieldNumber: 1)
    }
    if !self.secondInput.isEmpty {
      try visitor.visitSingularStringField(value: self.secondInput, fieldNumber: 2)
    }
    if self.forget != false {
      try visitor.visitSingularBoolField(value: self.forget, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_SetExchangePasswordReq, rhs: DGCLogin_SetExchangePasswordReq) -> Bool {
    if lhs.firstInput != rhs.firstInput {return false}
    if lhs.secondInput != rhs.secondInput {return false}
    if lhs.forget != rhs.forget {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_SetExchangePasswordResp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetExchangePasswordResp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_SetExchangePasswordResp, rhs: DGCLogin_SetExchangePasswordResp) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_VerifySmsCodeReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VerifySmsCodeReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "action"),
    2: .same(proto: "code"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.action) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.code) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.action != .login {
      try visitor.visitSingularEnumField(value: self.action, fieldNumber: 1)
    }
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_VerifySmsCodeReq, rhs: DGCLogin_VerifySmsCodeReq) -> Bool {
    if lhs.action != rhs.action {return false}
    if lhs.code != rhs.code {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_VerifySmsCodeResp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VerifySmsCodeResp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_VerifySmsCodeResp, rhs: DGCLogin_VerifySmsCodeResp) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_GetSmsCodeReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetSmsCodeReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .same(proto: "phone"),
    1: .same(proto: "country"),
    3: .standard(proto: "is_bind"),
    4: .same(proto: "action"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.country) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.phone) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isBind) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.action) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.country != 0 {
      try visitor.visitSingularInt32Field(value: self.country, fieldNumber: 1)
    }
    if !self.phone.isEmpty {
      try visitor.visitSingularStringField(value: self.phone, fieldNumber: 2)
    }
    if self.isBind != false {
      try visitor.visitSingularBoolField(value: self.isBind, fieldNumber: 3)
    }
    if self.action != .login {
      try visitor.visitSingularEnumField(value: self.action, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_GetSmsCodeReq, rhs: DGCLogin_GetSmsCodeReq) -> Bool {
    if lhs.phone != rhs.phone {return false}
    if lhs.country != rhs.country {return false}
    if lhs.isBind != rhs.isBind {return false}
    if lhs.action != rhs.action {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_GetSmsCodeReq.DGCAction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "Login"),
    1: .same(proto: "BindPhone"),
    2: .same(proto: "ChangePhone"),
    3: .same(proto: "etExchangePW"),
  ]
}

extension DGCLogin_GetSmsCodeRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetSmsCodeRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "is_register"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isRegister) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.isRegister != false {
      try visitor.visitSingularBoolField(value: self.isRegister, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_GetSmsCodeRes, rhs: DGCLogin_GetSmsCodeRes) -> Bool {
    if lhs.isRegister != rhs.isRegister {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_LoginWithPhoneSMSReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LoginWithPhoneSMSReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    4: .standard(proto: "device_id"),
    1: .same(proto: "country"),
    5: .standard(proto: "device_type"),
    2: .same(proto: "phone"),
    3: .standard(proto: "sms_token"),
    6: .same(proto: "channel"),
    7: .standard(proto: "sms_code"),
    8: .standard(proto: "account_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.country) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.phone) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.smsToken) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.deviceType) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.channel) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.smsCode) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.accountID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.country != 0 {
      try visitor.visitSingularInt32Field(value: self.country, fieldNumber: 1)
    }
    if !self.phone.isEmpty {
      try visitor.visitSingularStringField(value: self.phone, fieldNumber: 2)
    }
    if !self.smsToken.isEmpty {
      try visitor.visitSingularStringField(value: self.smsToken, fieldNumber: 3)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 4)
    }
    if self.deviceType != .dtUnknown {
      try visitor.visitSingularEnumField(value: self.deviceType, fieldNumber: 5)
    }
    if self.channel != 0 {
      try visitor.visitSingularInt32Field(value: self.channel, fieldNumber: 6)
    }
    if !self.smsCode.isEmpty {
      try visitor.visitSingularStringField(value: self.smsCode, fieldNumber: 7)
    }
    if self.accountID != 0 {
      try visitor.visitSingularInt64Field(value: self.accountID, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_LoginWithPhoneSMSReq, rhs: DGCLogin_LoginWithPhoneSMSReq) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.country != rhs.country {return false}
    if lhs.deviceType != rhs.deviceType {return false}
    if lhs.phone != rhs.phone {return false}
    if lhs.smsToken != rhs.smsToken {return false}
    if lhs.channel != rhs.channel {return false}
    if lhs.smsCode != rhs.smsCode {return false}
    if lhs.accountID != rhs.accountID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_LogoutReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LogoutReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "key"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_LogoutReq, rhs: DGCLogin_LogoutReq) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_LogoutRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LogoutRes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_LogoutRes, rhs: DGCLogin_LogoutRes) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_LoginReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LoginReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "key"),
    2: .same(proto: "deviceType"),
    3: .same(proto: "deviceId"),
    4: .standard(proto: "push_token"),
    5: .same(proto: "CountryCode"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.deviceType) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.pushToken) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.countryCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if self.deviceType != .dtUnknown {
      try visitor.visitSingularEnumField(value: self.deviceType, fieldNumber: 2)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 3)
    }
    if !self.pushToken.isEmpty {
      try visitor.visitSingularStringField(value: self.pushToken, fieldNumber: 4)
    }
    if !self.countryCode.isEmpty {
      try visitor.visitSingularStringField(value: self.countryCode, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_LoginReq, rhs: DGCLogin_LoginReq) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.deviceType != rhs.deviceType {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.pushToken != rhs.pushToken {return false}
    if lhs.countryCode != rhs.countryCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_LoginRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LoginRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "account_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt64Field(value: &self.accountID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.accountID != 0 {
      try visitor.visitSingularSInt64Field(value: self.accountID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_LoginRes, rhs: DGCLogin_LoginRes) -> Bool {
    if lhs.accountID != rhs.accountID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_DeleteAccountConfirmReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeleteAccountConfirmReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "code"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.code) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_DeleteAccountConfirmReq, rhs: DGCLogin_DeleteAccountConfirmReq) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_DeleteAccountConfirmRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeleteAccountConfirmRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "keep_days"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.keepDays) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.keepDays != 0 {
      try visitor.visitSingularInt32Field(value: self.keepDays, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_DeleteAccountConfirmRes, rhs: DGCLogin_DeleteAccountConfirmRes) -> Bool {
    if lhs.keepDays != rhs.keepDays {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_ZoneCountry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ZoneCountry"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "country_en"),
    2: .standard(proto: "country_name"),
    3: .standard(proto: "country_phone"),
    4: .same(proto: "position"),
    5: .standard(proto: "country_code"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.countryEn) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.countryName) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.countryPhone) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.position) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.countryCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.countryEn.isEmpty {
      try visitor.visitSingularStringField(value: self.countryEn, fieldNumber: 1)
    }
    if !self.countryName.isEmpty {
      try visitor.visitSingularStringField(value: self.countryName, fieldNumber: 2)
    }
    if self.countryPhone != 0 {
      try visitor.visitSingularInt64Field(value: self.countryPhone, fieldNumber: 3)
    }
    if self.position != 0 {
      try visitor.visitSingularInt32Field(value: self.position, fieldNumber: 4)
    }
    if !self.countryCode.isEmpty {
      try visitor.visitSingularStringField(value: self.countryCode, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_ZoneCountry, rhs: DGCLogin_ZoneCountry) -> Bool {
    if lhs.countryEn != rhs.countryEn {return false}
    if lhs.countryName != rhs.countryName {return false}
    if lhs.countryPhone != rhs.countryPhone {return false}
    if lhs.position != rhs.position {return false}
    if lhs.countryCode != rhs.countryCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_GetUserZoneReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetUserZoneReq"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_GetUserZoneReq, rhs: DGCLogin_GetUserZoneReq) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_GetUserZoneRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetUserZoneRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "default_index"),
    2: .same(proto: "country"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.defaultIndex) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.country) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.defaultIndex != 0 {
      try visitor.visitSingularInt32Field(value: self.defaultIndex, fieldNumber: 1)
    }
    if !self.country.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.country, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_GetUserZoneRes, rhs: DGCLogin_GetUserZoneRes) -> Bool {
    if lhs.defaultIndex != rhs.defaultIndex {return false}
    if lhs.country != rhs.country {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCLogin_BroadcastRelogin: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastRelogin"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "deviceId"),
    2: .standard(proto: "device_type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.deviceType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 1)
    }
    if self.deviceType != .dtUnknown {
      try visitor.visitSingularEnumField(value: self.deviceType, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCLogin_BroadcastRelogin, rhs: DGCLogin_BroadcastRelogin) -> Bool {
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.deviceType != rhs.deviceType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
