// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: privilege.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct DGCPrivilege_GetPrivilegeConfReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var md5: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPrivilege_GetPrivilegeConfRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 配置数据
  public var privilegeConf: [DGCPrivilege_PrivilegeConf] = []

  /// 0:需要使用配置更新本地缓存 非0 不用更新
  public var status: Int32 = 0

  /// 新的md5指纹
  public var md5: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPrivilege_PrivilegeConf {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 特权id
  public var userPrivilegeConfID: Int64 {
    get {return _storage._userPrivilegeConfID}
    set {_uniqueStorage()._userPrivilegeConfID = newValue}
  }

  /// 特权 类型
  public var privilegeTypeCode: DGCCommon_PrivilegeTypeCode {
    get {return _storage._privilegeTypeCode}
    set {_uniqueStorage()._privilegeTypeCode = newValue}
  }

  /// 特权 名称
  public var privilegeNm: String {
    get {return _storage._privilegeNm}
    set {_uniqueStorage()._privilegeNm = newValue}
  }

  /// 特权 图片
  public var privilegePict: String {
    get {return _storage._privilegePict}
    set {_uniqueStorage()._privilegePict = newValue}
  }

  /// 特权 动画
  public var privilegeAnimation: String {
    get {return _storage._privilegeAnimation}
    set {_uniqueStorage()._privilegeAnimation = newValue}
  }

  /// 特权 vip等级
  public var vipLevel: Int32 {
    get {return _storage._vipLevel}
    set {_uniqueStorage()._vipLevel = newValue}
  }

  /// 特权 配置数据
  public var privilegeConfData: DGCPrivilege_PrivilegeConfData {
    get {return _storage._privilegeConfData ?? DGCPrivilege_PrivilegeConfData()}
    set {_uniqueStorage()._privilegeConfData = newValue}
  }
  /// Returns true if `privilegeConfData` has been explicitly set.
  public var hasPrivilegeConfData: Bool {return _storage._privilegeConfData != nil}
  /// Clears the value of `privilegeConfData`. Subsequent reads from it will return its default value.
  public mutating func clearPrivilegeConfData() {_uniqueStorage()._privilegeConfData = nil}

  /// 特权 权重用于排序
  public var sort: Int32 {
    get {return _storage._sort}
    set {_uniqueStorage()._sort = newValue}
  }

  /// 特权描述
  public var privilegeDesc: String {
    get {return _storage._privilegeDesc}
    set {_uniqueStorage()._privilegeDesc = newValue}
  }

  ///形状类型
  public var style: Int32 {
    get {return _storage._style}
    set {_uniqueStorage()._style = newValue}
  }

  /// ios气泡图
  public var bubbleIos: String {
    get {return _storage._bubbleIos}
    set {_uniqueStorage()._bubbleIos = newValue}
  }

  /// android气泡图
  public var bubbleAndroid: String {
    get {return _storage._bubbleAndroid}
    set {_uniqueStorage()._bubbleAndroid = newValue}
  }

  /// 特权 动画（长），麦位特有资源
  public var privilegeAnimationLong: String {
    get {return _storage._privilegeAnimationLong}
    set {_uniqueStorage()._privilegeAnimationLong = newValue}
  }

  /// 特权 图片 阿语
  public var privilegePictAr: String {
    get {return _storage._privilegePictAr}
    set {_uniqueStorage()._privilegePictAr = newValue}
  }

  /// 特权 动画 阿语
  public var privilegeAnimationAr: String {
    get {return _storage._privilegeAnimationAr}
    set {_uniqueStorage()._privilegeAnimationAr = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct DGCPrivilege_PrivilegeConfData {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 嵌入到特权动画资源的参数，通常是：{"keyAvatar":"tagTOUXIANG","keyNickname":"tagWENZI"}
  public var embeddingData: String = String()

  /// 彩色昵称参数
  public var nicknameColors: [String] = []

  /// 资料卡背景
  public var cardBackground: String = String()

  /// 资料卡头像框
  public var cardFrame: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPrivilege_GetUserPrivilegesReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var playerID: Int64 = 0

  /// 是否返回全部的特权
  public var ifWithInvalid: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPrivilege_GetUserPrivilegesRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var userPrivilege: [DGCCommon_UserPrivilege] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPrivilege_SwitchUserPrivilegeReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 操作的用户特权id
  public var userPrivilegeID: Int64 = 0

  /// 传特权配置的id，适配vip特权
  public var privilegeConfID: Int64 = 0

  /// 是为开启，否则为关闭
  public var ifOn: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPrivilege_SwitchUserPrivilegeRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 开启用户特权后，需要关闭的用户特权。例如头像框只能有一个，会返回所有操作关闭的特权ID，方便客户端同步
  public var offPrivilegeID: [Int64] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPrivilege_BroadcastUpdateUserPrivilege {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Int64 = 0

  public var userPrivilegeConfID: Int64 = 0

  public var ifOn: Bool = false

  /// 特权数据，存放用户特有数据
  public var privilegeData: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPrivilege_RoomFrameListReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPrivilege_RoomFrame {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 房间边框唯一id
  public var relID: Int64 = 0

  /// 特权id
  public var userPrivilegeConfID: Int64 = 0

  /// 边框图片
  public var coverFrame: String = String()

  /// 边框过期时间，剩余秒数
  public var coverFrameOverTime: Int64 = 0

  /// 是否选中，如果列表全部false，表示选中默认边框
  public var isSelected: Bool = false

  /// 边框名称
  public var frameName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DGCPrivilege_RoomFrameListRes {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var list: [DGCPrivilege_RoomFrame] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension DGCPrivilege_GetPrivilegeConfReq: @unchecked Sendable {}
extension DGCPrivilege_GetPrivilegeConfRes: @unchecked Sendable {}
extension DGCPrivilege_PrivilegeConf: @unchecked Sendable {}
extension DGCPrivilege_PrivilegeConfData: @unchecked Sendable {}
extension DGCPrivilege_GetUserPrivilegesReq: @unchecked Sendable {}
extension DGCPrivilege_GetUserPrivilegesRes: @unchecked Sendable {}
extension DGCPrivilege_SwitchUserPrivilegeReq: @unchecked Sendable {}
extension DGCPrivilege_SwitchUserPrivilegeRes: @unchecked Sendable {}
extension DGCPrivilege_BroadcastUpdateUserPrivilege: @unchecked Sendable {}
extension DGCPrivilege_RoomFrameListReq: @unchecked Sendable {}
extension DGCPrivilege_RoomFrame: @unchecked Sendable {}
extension DGCPrivilege_RoomFrameListRes: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "privilege"

extension DGCPrivilege_GetPrivilegeConfReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetPrivilegeConfReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "md5"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.md5) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.md5.isEmpty {
      try visitor.visitSingularStringField(value: self.md5, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_GetPrivilegeConfReq, rhs: DGCPrivilege_GetPrivilegeConfReq) -> Bool {
    if lhs.md5 != rhs.md5 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPrivilege_GetPrivilegeConfRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetPrivilegeConfRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "privilegeConf"),
    2: .same(proto: "status"),
    3: .same(proto: "md5"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.privilegeConf) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.status) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.md5) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.privilegeConf.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.privilegeConf, fieldNumber: 1)
    }
    if self.status != 0 {
      try visitor.visitSingularInt32Field(value: self.status, fieldNumber: 2)
    }
    if !self.md5.isEmpty {
      try visitor.visitSingularStringField(value: self.md5, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_GetPrivilegeConfRes, rhs: DGCPrivilege_GetPrivilegeConfRes) -> Bool {
    if lhs.privilegeConf != rhs.privilegeConf {return false}
    if lhs.status != rhs.status {return false}
    if lhs.md5 != rhs.md5 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPrivilege_PrivilegeConf: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PrivilegeConf"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "user_privilege_conf_id"),
    2: .standard(proto: "privilege_type_code"),
    3: .standard(proto: "privilege_nm"),
    4: .standard(proto: "privilege_pict"),
    5: .standard(proto: "privilege_animation"),
    6: .standard(proto: "vip_level"),
    7: .standard(proto: "privilege_conf_data"),
    8: .same(proto: "sort"),
    9: .standard(proto: "privilege_desc"),
    10: .same(proto: "style"),
    11: .standard(proto: "bubble_ios"),
    12: .standard(proto: "bubble_android"),
    13: .standard(proto: "privilege_animation_long"),
    14: .standard(proto: "privilege_pict_ar"),
    15: .standard(proto: "privilege_animation_ar"),
  ]

  fileprivate class _StorageClass {
    var _userPrivilegeConfID: Int64 = 0
    var _privilegeTypeCode: DGCCommon_PrivilegeTypeCode = .ttcNil
    var _privilegeNm: String = String()
    var _privilegePict: String = String()
    var _privilegeAnimation: String = String()
    var _vipLevel: Int32 = 0
    var _privilegeConfData: DGCPrivilege_PrivilegeConfData? = nil
    var _sort: Int32 = 0
    var _privilegeDesc: String = String()
    var _style: Int32 = 0
    var _bubbleIos: String = String()
    var _bubbleAndroid: String = String()
    var _privilegeAnimationLong: String = String()
    var _privilegePictAr: String = String()
    var _privilegeAnimationAr: String = String()

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _userPrivilegeConfID = source._userPrivilegeConfID
      _privilegeTypeCode = source._privilegeTypeCode
      _privilegeNm = source._privilegeNm
      _privilegePict = source._privilegePict
      _privilegeAnimation = source._privilegeAnimation
      _vipLevel = source._vipLevel
      _privilegeConfData = source._privilegeConfData
      _sort = source._sort
      _privilegeDesc = source._privilegeDesc
      _style = source._style
      _bubbleIos = source._bubbleIos
      _bubbleAndroid = source._bubbleAndroid
      _privilegeAnimationLong = source._privilegeAnimationLong
      _privilegePictAr = source._privilegePictAr
      _privilegeAnimationAr = source._privilegeAnimationAr
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let dgc_fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch dgc_fieldNumber {
        case 1: try { try decoder.decodeSingularInt64Field(value: &_storage._userPrivilegeConfID) }()
        case 2: try { try decoder.decodeSingularEnumField(value: &_storage._privilegeTypeCode) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._privilegeNm) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._privilegePict) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._privilegeAnimation) }()
        case 6: try { try decoder.decodeSingularInt32Field(value: &_storage._vipLevel) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._privilegeConfData) }()
        case 8: try { try decoder.decodeSingularInt32Field(value: &_storage._sort) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._privilegeDesc) }()
        case 10: try { try decoder.decodeSingularInt32Field(value: &_storage._style) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._bubbleIos) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._bubbleAndroid) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._privilegeAnimationLong) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._privilegePictAr) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._privilegeAnimationAr) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._userPrivilegeConfID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._userPrivilegeConfID, fieldNumber: 1)
      }
      if _storage._privilegeTypeCode != .ttcNil {
        try visitor.visitSingularEnumField(value: _storage._privilegeTypeCode, fieldNumber: 2)
      }
      if !_storage._privilegeNm.isEmpty {
        try visitor.visitSingularStringField(value: _storage._privilegeNm, fieldNumber: 3)
      }
      if !_storage._privilegePict.isEmpty {
        try visitor.visitSingularStringField(value: _storage._privilegePict, fieldNumber: 4)
      }
      if !_storage._privilegeAnimation.isEmpty {
        try visitor.visitSingularStringField(value: _storage._privilegeAnimation, fieldNumber: 5)
      }
      if _storage._vipLevel != 0 {
        try visitor.visitSingularInt32Field(value: _storage._vipLevel, fieldNumber: 6)
      }
      try { if let dgc_v = _storage._privilegeConfData {
        try visitor.visitSingularMessageField(value: dgc_v, fieldNumber: 7)
      } }()
      if _storage._sort != 0 {
        try visitor.visitSingularInt32Field(value: _storage._sort, fieldNumber: 8)
      }
      if !_storage._privilegeDesc.isEmpty {
        try visitor.visitSingularStringField(value: _storage._privilegeDesc, fieldNumber: 9)
      }
      if _storage._style != 0 {
        try visitor.visitSingularInt32Field(value: _storage._style, fieldNumber: 10)
      }
      if !_storage._bubbleIos.isEmpty {
        try visitor.visitSingularStringField(value: _storage._bubbleIos, fieldNumber: 11)
      }
      if !_storage._bubbleAndroid.isEmpty {
        try visitor.visitSingularStringField(value: _storage._bubbleAndroid, fieldNumber: 12)
      }
      if !_storage._privilegeAnimationLong.isEmpty {
        try visitor.visitSingularStringField(value: _storage._privilegeAnimationLong, fieldNumber: 13)
      }
      if !_storage._privilegePictAr.isEmpty {
        try visitor.visitSingularStringField(value: _storage._privilegePictAr, fieldNumber: 14)
      }
      if !_storage._privilegeAnimationAr.isEmpty {
        try visitor.visitSingularStringField(value: _storage._privilegeAnimationAr, fieldNumber: 15)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_PrivilegeConf, rhs: DGCPrivilege_PrivilegeConf) -> Bool {
    if lhs.dgc__storage !== rhs.dgc__storage {
      let dgc_storagesAreEqual: Bool = withExtendedLifetime((lhs.dgc__storage, rhs.dgc__storage)) { (_args: (_StorageClass, _StorageClass)) in
        let dgc__storage = _args.0
        let dgc_rhs_storage = _args.1
        if dgc__storage._userPrivilegeConfID != dgc_rhs_storage._userPrivilegeConfID {return false}
        if dgc__storage._privilegeTypeCode != dgc_rhs_storage._privilegeTypeCode {return false}
        if dgc__storage._privilegeNm != dgc_rhs_storage._privilegeNm {return false}
        if dgc__storage._privilegePict != dgc_rhs_storage._privilegePict {return false}
        if dgc__storage._privilegeAnimation != dgc_rhs_storage._privilegeAnimation {return false}
        if dgc__storage._vipLevel != dgc_rhs_storage._vipLevel {return false}
        if dgc__storage._privilegeConfData != dgc_rhs_storage._privilegeConfData {return false}
        if dgc__storage._sort != dgc_rhs_storage._sort {return false}
        if dgc__storage._privilegeDesc != dgc_rhs_storage._privilegeDesc {return false}
        if dgc__storage._style != dgc_rhs_storage._style {return false}
        if dgc__storage._bubbleIos != dgc_rhs_storage._bubbleIos {return false}
        if dgc__storage._bubbleAndroid != dgc_rhs_storage._bubbleAndroid {return false}
        if dgc__storage._privilegeAnimationLong != dgc_rhs_storage._privilegeAnimationLong {return false}
        if dgc__storage._privilegePictAr != dgc_rhs_storage._privilegePictAr {return false}
        if dgc__storage._privilegeAnimationAr != dgc_rhs_storage._privilegeAnimationAr {return false}
        return true
      }
      if !dgc_storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPrivilege_PrivilegeConfData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PrivilegeConfData"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "EmbeddingData"),
    2: .standard(proto: "nickname_colors"),
    3: .standard(proto: "card_background"),
    4: .standard(proto: "card_frame"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.embeddingData) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.nicknameColors) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.cardBackground) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.cardFrame) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.embeddingData.isEmpty {
      try visitor.visitSingularStringField(value: self.embeddingData, fieldNumber: 1)
    }
    if !self.nicknameColors.isEmpty {
      try visitor.visitRepeatedStringField(value: self.nicknameColors, fieldNumber: 2)
    }
    if !self.cardBackground.isEmpty {
      try visitor.visitSingularStringField(value: self.cardBackground, fieldNumber: 3)
    }
    if !self.cardFrame.isEmpty {
      try visitor.visitSingularStringField(value: self.cardFrame, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_PrivilegeConfData, rhs: DGCPrivilege_PrivilegeConfData) -> Bool {
    if lhs.embeddingData != rhs.embeddingData {return false}
    if lhs.nicknameColors != rhs.nicknameColors {return false}
    if lhs.cardBackground != rhs.cardBackground {return false}
    if lhs.cardFrame != rhs.cardFrame {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPrivilege_GetUserPrivilegesReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetUserPrivilegesReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "playerId"),
    2: .same(proto: "ifWithInvalid"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.playerID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.ifWithInvalid) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.playerID != 0 {
      try visitor.visitSingularInt64Field(value: self.playerID, fieldNumber: 1)
    }
    if self.ifWithInvalid != false {
      try visitor.visitSingularBoolField(value: self.ifWithInvalid, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_GetUserPrivilegesReq, rhs: DGCPrivilege_GetUserPrivilegesReq) -> Bool {
    if lhs.playerID != rhs.playerID {return false}
    if lhs.ifWithInvalid != rhs.ifWithInvalid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPrivilege_GetUserPrivilegesRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetUserPrivilegesRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "userPrivilege"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.userPrivilege) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.userPrivilege.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.userPrivilege, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_GetUserPrivilegesRes, rhs: DGCPrivilege_GetUserPrivilegesRes) -> Bool {
    if lhs.userPrivilege != rhs.userPrivilege {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPrivilege_SwitchUserPrivilegeReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SwitchUserPrivilegeReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "user_privilege_id"),
    2: .standard(proto: "privilege_conf_id"),
    3: .standard(proto: "if_on"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.userPrivilegeID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.privilegeConfID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.ifOn) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.userPrivilegeID != 0 {
      try visitor.visitSingularInt64Field(value: self.userPrivilegeID, fieldNumber: 1)
    }
    if self.privilegeConfID != 0 {
      try visitor.visitSingularInt64Field(value: self.privilegeConfID, fieldNumber: 2)
    }
    if self.ifOn != false {
      try visitor.visitSingularBoolField(value: self.ifOn, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_SwitchUserPrivilegeReq, rhs: DGCPrivilege_SwitchUserPrivilegeReq) -> Bool {
    if lhs.userPrivilegeID != rhs.userPrivilegeID {return false}
    if lhs.privilegeConfID != rhs.privilegeConfID {return false}
    if lhs.ifOn != rhs.ifOn {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPrivilege_SwitchUserPrivilegeRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SwitchUserPrivilegeRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "off_privilege_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedInt64Field(value: &self.offPrivilegeID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.offPrivilegeID.isEmpty {
      try visitor.visitPackedInt64Field(value: self.offPrivilegeID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_SwitchUserPrivilegeRes, rhs: DGCPrivilege_SwitchUserPrivilegeRes) -> Bool {
    if lhs.offPrivilegeID != rhs.offPrivilegeID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPrivilege_BroadcastUpdateUserPrivilege: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BroadcastUpdateUserPrivilege"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .standard(proto: "user_privilege_conf_id"),
    3: .same(proto: "ifOn"),
    4: .standard(proto: "privilege_data"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularSInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.userPrivilegeConfID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.ifOn) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.privilegeData) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularSInt64Field(value: self.id, fieldNumber: 1)
    }
    if self.userPrivilegeConfID != 0 {
      try visitor.visitSingularInt64Field(value: self.userPrivilegeConfID, fieldNumber: 2)
    }
    if self.ifOn != false {
      try visitor.visitSingularBoolField(value: self.ifOn, fieldNumber: 3)
    }
    if !self.privilegeData.isEmpty {
      try visitor.visitSingularStringField(value: self.privilegeData, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_BroadcastUpdateUserPrivilege, rhs: DGCPrivilege_BroadcastUpdateUserPrivilege) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.userPrivilegeConfID != rhs.userPrivilegeConfID {return false}
    if lhs.ifOn != rhs.ifOn {return false}
    if lhs.privilegeData != rhs.privilegeData {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPrivilege_RoomFrameListReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RoomFrameListReq"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_RoomFrameListReq, rhs: DGCPrivilege_RoomFrameListReq) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPrivilege_RoomFrame: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RoomFrame"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "rel_id"),
    2: .standard(proto: "user_privilege_conf_id"),
    3: .standard(proto: "cover_frame"),
    4: .standard(proto: "cover_frame_over_time"),
    5: .standard(proto: "is_selected"),
    6: .standard(proto: "frame_name"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.relID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.userPrivilegeConfID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.coverFrame) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.coverFrameOverTime) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.isSelected) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.frameName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.relID != 0 {
      try visitor.visitSingularInt64Field(value: self.relID, fieldNumber: 1)
    }
    if self.userPrivilegeConfID != 0 {
      try visitor.visitSingularInt64Field(value: self.userPrivilegeConfID, fieldNumber: 2)
    }
    if !self.coverFrame.isEmpty {
      try visitor.visitSingularStringField(value: self.coverFrame, fieldNumber: 3)
    }
    if self.coverFrameOverTime != 0 {
      try visitor.visitSingularInt64Field(value: self.coverFrameOverTime, fieldNumber: 4)
    }
    if self.isSelected != false {
      try visitor.visitSingularBoolField(value: self.isSelected, fieldNumber: 5)
    }
    if !self.frameName.isEmpty {
      try visitor.visitSingularStringField(value: self.frameName, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_RoomFrame, rhs: DGCPrivilege_RoomFrame) -> Bool {
    if lhs.relID != rhs.relID {return false}
    if lhs.userPrivilegeConfID != rhs.userPrivilegeConfID {return false}
    if lhs.coverFrame != rhs.coverFrame {return false}
    if lhs.coverFrameOverTime != rhs.coverFrameOverTime {return false}
    if lhs.isSelected != rhs.isSelected {return false}
    if lhs.frameName != rhs.frameName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DGCPrivilege_RoomFrameListRes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RoomFrameListRes"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "list"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let dgc_fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch dgc_fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.list) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.list.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.list, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DGCPrivilege_RoomFrameListRes, rhs: DGCPrivilege_RoomFrameListRes) -> Bool {
    if lhs.list != rhs.list {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
